### PR TITLE
Resolve #2313

### LINKED ISSUE #2313: "markdown-it-attrs limitation: New line attributes not correctly assigned to list items"
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2272

### Tell us about your environment

Window 10

### MarkBind version

 v4.1.0

### Describe the bug and the steps to reproduce it

Consider the following code:

```
* item 1
* item 2 
  * item 2.1
  * item 2.2
  
  {icons="light-bulb"}
* item 3

{icons="thumbs-up"}
```
Here is the rendered output:

248452486-8deb39ba-782b-42a4-9b6b-9eec5a4d441b

Observe that despite both the nested list and the outer list being declared identically, they render differently in HTML.

Innermost list items are output as standalone <li> elements, whereas the outer list items are wrapped within <li><p>{item}</p></li>. This inconsistency suggests a potential bug in our current processing pipeline, meriting further investigation and potentially the filing of a new issue.

However, all parameters are preserved, enabling DOM manipulation to achieve the desired output. Consequently, we should refine our processing pipeline to standardize and bring consistency to the output, thereby enhancing the predictability and reliability of our rendering process.

### Expected behavior

Both outer layer and inter layer should be render the same way:
Code:
```
* item 1 Without P Fix this
  * item 1.1 With P

  * item 1.2 With P
* item 2 Without P Fix this
  * item 2.1 With P
    * item 2.1 Without P
    * item 2.2 Without P

  * item 2.2 With P
* item 3 Without P Fix this
  * item 3.1 Without P Fix this
    * item 3.1.1 Without P
    * item 3.1.2 Without P
  * item 3.2 Without P Fix this

  {icons="light-3"}
* item 4 Without P Fix this
  * item 4.1 With P 
    * item 4.1.1 Without P
    * item 4.1.2 Without P
    
  * item 4.2 With P 

  {icons="light-4"}

{icons="thumbs-up"}
```

Output:
image

### Anything else?

Here is an improved version with some grammatical corrections and additions of Markdown code formatting:

Please refer to the official markdown-it-attrs documentation on GitHub for an explanation of ambiguous syntax: [markdown-it-attrs Ambiguity Syntax](https://github.com/arve0/markdown-it-attrs#Ambiguity).

The recommended way of declaring block variables is not consistent and intuitive. Therefore, a standardization and improvement is required. It might look something like this:

```
* item 1 With P Fix this
  * item 1.1 With P

  * item 1.2 With P
* item 2 With P Fix this
  * item 2.1 With P
    * item 2.1 Without P
    * item 2.2 Without P

  * item 2.2 With P
  
  {icons="light-2"}
* item 3 With P Fix this
  * item 3.1 Without P Fix this
    * item 3.1.1 Without P
    * item 3.1.2 Without P
  * item 3.2 Without P Fix this

  {icons="light-3"}
* item 4 With P Fix this
  * item 4.1 With P Fix this
    * item 4.1.1 Without P
    * item 4.1.2 Without P
    
  * item 4.2 With P Fix this

  {icons="light-4"}

{icons="thumbs-up"}

```

### PR DESCRIPTION
**Pull request by SPWwj**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Example Code:
```
* item 1 Without P Fix this
  * item 1.1 With P

  * item 1.2 With P
* item 2 Without P Fix this
  * item 2.1 With P
    * item 2.1 Without P
    * item 2.2 Without P

  * item 2.2 With P
* item 3 Without P Fix this
  * item 3.1 Without P Fix this
    * item 3.1.1 Without P
    * item 3.1.2 Without P
  * item 3.2 Without P Fix this

  {icons="light-3"}
* item 4 Without P Fix this
  * item 4.1 With P 
    * item 4.1.1 Without P
    * item 4.1.2 Without P
    
  * item 4.2 With P 

  {icons="light-4"}

{icons="thumbs-up"}
```
Previous Output:

248566118-c425a05d-9f0a-4d4b-93aa-aad8e10d2dca

Current Ouput:
image

**Anything you'd like to highlight/discuss:**

**Testing instructions:**
Please consider checking out the code locally and testing with various syntax configurations to verify if the unordered list (ul) rendering yields the expected output.

Example:
```
* item 1 Without P Fix this
  * item 1.1 With P

  * item 1.2 With P
* item 2 Without P Fix this
  * item 2.1 With P
    * item 2.1 Without P
    * item 2.2 Without P

  * item 2.2 With P
* item 3 Without P Fix this
  * item 3.1 Without P Fix this
    * item 3.1.1 Without P
    * item 3.1.2 Without P
  * item 3.2 Without P Fix this

  {icons="light-3"}
* item 4 Without P Fix this
  * item 4.1 With P 
    * item 4.1.1 Without P
    * item 4.1.2 Without P
    
  * item 4.2 With P 

  {icons="light-4"}

{icons="thumbs-up"}
```

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [X] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes

### CODE REVIEW

**Comment by ang-zeyu** [comment]
Thanks for the detailed examples and investigation! They're really easy to follow and reproduce.

I have not looked at the code but my comments on the output alone:

1. The first one is what I've mentioned here https://github.com/MarkBind/markbind/issues/2313#issuecomment-1607422731
   > We cannot say for sure if the author meant to put a tight (forced by markdown-it-attrs) or loose (where and when the author already wanted one) list.

   I do not think this can be overcome without *discussion on the syntax upstream*, or at least I can't think of a workaround right now.

   The list containing `item 3.1 Without P Fix this` and `item 3.2 Without P Fix this` is an example of this ambiguity.

2. `item 1.1 With P` belongs in a loose list but oddly it looks like the spacing on top of it was removed. The same goes for `2.1 with P, 2.2 with P, 4.1 with P, 4.2 with P`.
   image

**Comment by SPWwj** [comment]
> 1.
Yes, the code in this PR is quite complex. I haven't corrected the syntax for the CI test yet due to potential inaccuracies, pending further testing. However, it does propose a potential solution to the syntax issues.

consider this:
```
- a
  - a
    - a  {.applies-to-first-nested-list}
  
  {.applies-to-first-nested-list}
  {.applies-to-first-nested-list}
  {.applies-to-first-nested-list}
- a
```
Based on the instructions in markdown-it attri, the outcome might not be as expected due to potential overriding of certain {} elements.

2. This is because the p tag has the margin-bottom only, sorry that I did not include the html screenshot:
image

**Comment by ang-zeyu** [comment]
My doubt isn't on the implementation or where it should be placed, but whether we can achieve the same core feature set of loose & tight lists. If it is not possible, I think we should bring up the syntax upstream as the maintainer likely has far more nuance and context into its design.

Let's use your example:

```
* item 4 Without P Fix this
  * item 4.1 With P 
    * item 4.1.1 Without P
    * item 4.1.2 Without P
    
  * item 4.2 With P

  {icons="light-4"}
```

Without this change, the outer list would be a loose list due to the blank line.

With this change, it would be corrected to a tight list, which I agree is a more intuitive option as well.

What if the author wanted to make it a loose list while still specifying the attributes however?
Is that still possible? (Implementation wise too)

**Comment by ang-zeyu** [comment]
Implementation wise,

> Moreover, not all issues are addressed upstream, evidenced by numerous popular libraries untouched for years.

They are certainly not, but I'd try and see if this can be accepted upstream first as it would benefit not just this project but others relying on markdown-it-attrs too. If there are further issues down the line we'd benefit from upstream updates as well.

> Additionally, this PR doesn't alter the internal implementation of markdown-it or markdown-it-attrs. > It merely checks if the syntax we've defined is applied. If so, we need to eliminate the impact of our syntax on the markdown-to-HTML rendering process.

I haven't looked at the code here deeply but another thing you can consider is if altering the project directly would lead to a simpler and performant implemention. Along these lines, if the maintainer isn't able to accept the additional load, you can consider forking (or just copy pasting it over). (We can give you the necessary permissions here if needed)

**Pull request closed without merging**
