### PR TITLE
Fixed: Broken link in About Us #1800

### LINKED ISSUE #1800: Broken link in About Us
**Tell us about your environment**
Windows
* **MarkBind Version:**
* v3.1.1

**What did you do? Please include the actual source code causing the issue.**
https://markbind.org/about.html
The link to [NUS Center for Development of Teaching and Learning](http://www.cdtl.nus.edu.sg/) is broken.
**What did you expect to happen?**
No broken links.

**What actually happened? Please include the actual, raw output.**
The reference NUS site seems to be down/shifted. Not sure what's the latest URL for it. 

Btw this seems to also affect other NUS OSS projects, e.g TEAMMATES.

### PR DESCRIPTION
**Pull request by NaincyKumariKnoldus**
Hey @tlylt I have fixed the link in About Us. I have updated it to https://nus.edu.sg/cdtl.
Please Review my PR.
Thanks!

Reviewer(tlylt) edits:
Fixes #1800 
**Proposed commit message: (wrap lines at 72 characters)**
Fix broken link in UG's About Us page

### CODE REVIEW

**Review by jovyntls — APPROVED** [review]
LGTM! Thank you for contributing :)

**Comment by NaincyKumariKnoldus** [comment]
> LGTM! Thank you for contributing :)

Can you merge my PR as you have approved this.

**Comment by tlylt** [comment]
> > LGTM! Thank you for contributing :)
> 
> Can you merge my PR as you have approved this.

Hi @NaincyKumariKnoldus, thank you for raising the PR!

Just a friendly reminder: would be great if the PR description follows the PR template as specified [here](https://github.com/MarkBind/markbind/blob/master/.github/PULL_REQUEST_TEMPLATE) so that all relevant information is included. You may refer to other ongoing PRs for an example. e.g https://github.com/MarkBind/markbind/pull/1797

Otherwise LGTM (will be merged once one of our senior devs has taken a final look, thank you for your patience!)

**Review by ryoarmanda — APPROVED** [review]
LGTM!

**Pull request merged**
