### PR TITLE
Use a more noticeable color for highlight words in fenced code (#2051)

### LINKED ISSUE #2051: Use a more noticeable color for highlight words in fenced code
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

n/a

### MarkBind version

4.0.2

### What did you do? Describe the bug

When the dark theme is used (which is the default) for fenced code, the highlighted words are not easy to spot.

image

### Steps to reproduce

as above

### Expected behavior

Use a color more easily visible in both dark and light themes, or use different colors for the two different themes?

### Actual behavior

as abve

### Anything else?

n/a

### PR DESCRIPTION
**Pull request by Tim-Siu**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [x] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**

Resolves #2051

The highlighting color for fenced code block in dark theme is changed to from grey 474949 to complete dark 000000.

Citing @yucheng11122017 
> The dark and light themes already have different colors 474949 for their highlighting. (#474949 for dark and #e6e6fa for light)
> 
> [Docusaurus ](https://docusaurus.io/docs/markdown-features/code-blocks)uses a brighter color for their dark theme code highlighting (#646464). They allow users to override the default background color.
> 
> Using that value, this is what the code highlighting looks like which does seem a bit too bright making it hard to read the text

**Anything you'd like to highlight/discuss:**

**Testing instructions:**
Screenshot 2024-01-29 at 17 22 09

**Proposed commit message: (wrap lines at 72 characters)**

Use a more noticeable color for highlight words in fenced code under dark theme

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Review by yucheng11122017 — COMMENTED** [review]
Thanks for the work @Tim-Siu! 
Could you also update the css file for the docs and the templates as well? Otherwise, it is not reflected in these files. 
Also, I'm looking at the code block right now and it doesn't look very nice. 
What I actually meant with my comment was to change it a darker color like #000000. 
Could we change it to use #000000 instead? 
image

**Comment by Tim-Siu** [comment]
> Thanks for the work @Tim-Siu! Could you also update the css file for the docs and the templates as well? Otherwise, it is not reflected in these files. Also, I'm looking at the code block right now and it doesn't look very nice. What I actually meant with my comment was to change it a darker color like #000000. Could we change it to use #000000 instead? image

Hi Yucheng,

I apologize for any confusion regarding your earlier request. I have now revised the highlight color in the code block to pure black (#000000), as per your specification.

Regarding the update of the CSS files for the documentation and templates, I would like to clarify the process. My understanding is that the CSS files within the `_site` directory are auto-generated. Could you please clarify the steps needed for this integration?

**Review by yucheng11122017 — APPROVED** [review]
Hi @Tim-Siu sorry for my previous comment! Yes you are right, there should be no change needed anymore. Thanks for the work on the PR!
LGTM

**Review by tlylt — DISMISSED** [review]
@Tim-Siu this [place](https://deploy-preview-2394--markbind-master.netlify.app/userguide/formattingcontents#themes) in our docs needs to be updated?
image


Is the issue description up-to-date? Which color are we using in the end? Could you update the issue description to include a clear example of before and after for comparison pls

**Comment by Tim-Siu** [comment]
> @Tim-Siu this [place](https://deploy-preview-2394--markbind-master.netlify.app/userguide/formattingcontents#themes) in our docs needs to be updated? image
> 
> Is the issue description up-to-date? Which color are we using in the end? Could you update the issue description to include a clear example of before and after for comparison pls

Sorry for the oversight and thank you for pointing it out!

As there is no local control for the code theme in Markbind, I updated the screenshot used in the UG. I updated the PR description as well.

**Comment by tlylt** [comment]
Pinging @damithc for opinions on the visual change.

**Comment by damithc** [comment]
> Pinging @damithc for opinions on the visual change.

I'm OK with it 👍

**Pull request merged**
