### PR TITLE
Update Breadcrumb icons

### PR DESCRIPTION
**Pull request by itsyme**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [x] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Added a ">>" before the start of breadcrumbs and changed the icons between links of breadcrumbs to ">" to increase clarity.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Update Breadcrumb icons

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Comment by yucheng11122017** [comment]
Hi @itsyme, understand that @damithc prefers this implementation but I actually thought that using slash is better for breadcrumbs. Other sites also use slash and would be good to be consistent with them. 
The slash also looks nicer imo

**Comment by damithc** [comment]
@yucheng11122017 Using the slash is fine if there is no confusion when there is a slash in the text itself. Perhaps the slash can be formatted differently from the text?

Also dig around resources such as this to see if there are relevant ideas https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

**Comment by yucheng11122017** [comment]
> @yucheng11122017 Using the slash is fine if there is no confusion when there is a slash in the text itself. Perhaps the slash can be formatted differently from the text?
> 
> Also dig around resources such as this to see if there are relevant ideas https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

Oh I see your concern Prof. I found some icons which I think may work and imo looks nicer than the current fix

[Glyphicons menu right ](https://getbootstrap.com/docs/3.3/components/#glyphicons:~:text=glyphicon%20glyphicon%2Dmenu%2Dright)
[Octicon File ref](https://primer.style/design/foundations/icons/rel-file-path-24)

Not sure if this is useful @itsyme

**Comment by itsyme** [comment]
Thank you for the feedback @damithc @yucheng11122017! What do you think about the below? I feel that it makes the square brackets make the breadcrumb look less like stray text and the pipe would help reduce the confusion between text and the breadcrumb separator as pipe would be much less common in titles.

Screenshot 2023-04-03 at 3 51 26 PM

Screenshot 2023-04-03 at 3 51 57 PM

**Comment by lhw-1** [comment]
Some possible ideas for the design as well:

https://mui.com/material-ui/react-breadcrumbs/
https://mui.com/joy-ui/react-breadcrumbs/
https://component.gallery/components/breadcrumbs/

Personally, I think arrows ([Glyphicons menu right](https://getbootstrap.com/docs/3.3/components/#glyphicons:~:text=glyphicon%20glyphicon%2Dmenu%2Dright) as suggested by @yucheng11122017) or emboldened backslash might work well with the square brackets?

**Review by yucheng11122017 — APPROVED** [review]
LGTM!

**Comment by itsyme** [comment]
Hi @damithc! I was wondering if the updated icons for breadcrumbs are to your liking?

**Comment by damithc** [comment]
> Hi @damithc! I was wondering if the latest icons for breadcrumbs are to your liking?

@itsyme Yup, looks good 👍

**Pull request merged**
