### PR TITLE
Tweak pull request template

### PR DESCRIPTION
**Pull request by ang-zeyu**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [x] Others, please explain: Improve pull request template

**Overview of changes:**
- removed code example section, I found myself often skipping over it and just going straight to files tab
- added a PR checklist
- Merged rationale, purpose and linked issues sections
- Tweaked some wording

**Anything you'd like to highlight / discuss:**
- Anything we should add / remove in the checklist?
- Wording

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Tweak pull request template

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No blatantly unrelated changes
- [x] Pinged someone for a review!

### CODE REVIEW

**Comment by ang-zeyu** [comment]
@KendrickAng @wxwxwxwx9 @ryoarmanda

I removed and merged some sections which I felt were pressuring contributors to fill unnecessarily 
Also added a checklist; Items sourced from other repos 

Would appreciate any opinions / suggestions you have! :)

**Comment by ang-zeyu** [comment]
any thoughts / suggestions? if not I'll merge this in a while

@KendrickAng @ryoarmanda @wxwxwxwx9

**Comment by KendrickAng** [comment]
LGTM! The template requires contributors to make clear what it's addressing at that moment, and also includes a rationale section for people in the future to understand the context of the PR.

**Comment by ryoarmanda** [comment]
It looks great :+1: appreciate the checklist too, both contributors and reviewers can now easily keep track with the admin/testing progress of the PR

**Comment by wxwxwxwx9** [comment]
Sorry for the late reply! I think it fits our current workflow better as well. LGTM! Thanks for the update!

**Comment by ang-zeyu** [comment]
Thanks for the comments @ryoarmanda @KendrickAng @wxwxwxwx9 🙂
 I'll merge this in then, feel free to ping back here if anything feels out of place later

**Pull request merged**
