### PR TITLE
Migrate to Bootstrap 5

### LINKED ISSUE #1702: Bootstrap 5
Looks like Bootstrap has moved to v5

Some new things I noticed in passing: built-in support for icons, themes

### PR DESCRIPTION
**Pull request by jovyntls**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] Others, please explain:

Fixes #1702

**Overview of changes:**
Migrate Bootstrap to v5.1.3 

**Anything you'd like to highlight / discuss:**
Breaking change to MarkBind: `text-dark` now needs to be manually applied on badges with `bg-warning`, `bg-info`, `bg-light` (previously text would automatically be dark for these classes).

**Testing instructions:**
- Full functionality should be supported
- No disruptive changes in the UI
	- Major UI changes should be listed below

**Proposed commit message: (wrap lines at 72 characters)**
```
Migrate Bootstrap to v5.1.3
```

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

# Breaking Changes (for MarkBind)

- `text-dark` must be manually applied for `bg-warning`, `bg-info`, `bg-light` (previously text would automatically be dark for these classes).

# Notable UI Changes

| Before | After |
| --- | --- |
| **Theme colours**: Lower contrast (applies to any component using Bootstrap theme colours, e.g. badges, tipboxes) | Increased contrast. See badges for comparison | 
|  | **Badges**: increased padding  |
| Screenshot 2022-04-09 at 1 50 23 AM | **Tables**: Divider between table header and body Screenshot 2022-04-09 at 1 50 11 AM Less padding in tables |
| image | **Panels**: Slimmer panel, less padding image |
| image | **Popovers**: Border below popover headers; increased padding image |
| No RFS (Responsive Font Sizes) | RFS support: font sizes are now scaled relative to the viewport, instead of absolute. (e.g. h1 on a smaller screen will be smaller than h1 on a larger screen) |

# Breaking Changes in Bootstrap 4 -> 5

This list serves to account for all the changes needed/made for this migration. 
Full list of breaking changes from Bootstrap 4->5 may be found in the [Bootstrap migration docs](https://getbootstrap.com/docs/5.0/migration/).

### Utilities
- [x] `.float-left` and `.float-right` -> `.float-start` and `.float-end` (#1834)
- [x] `.font-weight-*` -> `.fw-*` (#1834)
- [x] `.ml-*` and `mr-*` -> `ms-*` and `me-*` (#1834)
- [x] `.pl-*` and `pr-*` -> `ps-*` and `pe-*` (#1834)
- [x] All other breaking changes do not affect MarkBind

### Components
- [x] ~~Accordion~~ (new component - no action needed)
- [x] ~~Alerts~~ (not used - no action needed)
- [x] Badges (#1884)
	- [x] `.badge-*` color classes -> `.bg-*`
	- [x] `.badge-pill` -> `.rounded-pill`
- [x] ~~Breadcrumbs~~ (not used - no action needed)
- [x] ~~Buttons~~ (breaking changes won't affect us)
- [x] ~~Card~~ (breaking changes won't affect us)
- [x] ~~Carousel~~ (not used - no action needed)
- [x] Close button (#1886)
- [x] ~~Collapse~~ (not used - no action needed)
- [x] Dropdowns (#1888)
- [x] Jumbotron (#1885)
	- not supported by MarkBind officially, only used for styling docs
- [x] ~~List group~~ (only new additions - no action needed)
- [x] ~~Navs and tabs~~ (only new additions - no action needed)
- [x] ~~Navbars~~ (#1906)
- [x] ~~Offcanvas~~ (new component - no action needed)
- [x] ~~Pagination~~ (only new additions - no action required)
- [x] ~~Popovers~~ (not used - no action needed)
- [x] ~~Spinners~~ (not used - no action needed) 
- [x] ~~Toasts~~ (not used - no action needed)
- [x] ~~Tooltips~~ (not used - no action needed)

### Sass 
- [x] (not used in MarkBind, no action needed)

### Color system
- [x] (not used in MarkBind, no action needed)

### Grid updates
- [x] Several changes in default positioning 
	- [x] Directly affected: `QOption` (#1890)
	- [x] Indirectly affected: Navbar padding (#1900)
	- [x] Indirectly affected: Some changes in padding, either reverted or listed below under "Notable UI Changes"

### Content, Reboot, etc
- [x] Remove newly default underline for links (#1834)
- [x] `<hr>` is no longer implemented using borders (#1901)

### RTL
- [x] Horizontal direction specific variables, utilities, and mixins have all been renamed to use logical properties like those found in flexbox layouts—e.g., start and end in lieu of left and right.

### Forms
- [x] Dropped classes are not used anywhere in MarkBind 

### Helpers
- [x] All changes do not affect MarkBind

### JavaScript
- [x] Data attributes are now namespaced with `data-bs` (#1892)
	- accounted for: toggle, spy, parent, target, offset, method, dismiss
- [x] All other changes do not affect MarkBind

# Other changes required
- [x] Dependencies on Bootstrap 4 are removed (bootstrap-vue removed in #1849, #1856, #1868)
- [x] Bootswatch is bumped to v5.1.3 (#1898)

### CODE REVIEW

**Comment by jonahtanjz** [comment]
> Indirectly affected: to check manually afterwards

Not sure if you can see it but on the mobile navbar, will need to remove the spacing at the sides. Probably related to the grid updates.

image

Will also need to give some padding to the navbar in general.

Before:
image

After (A little bit tight around the edges):
image

**Comment by jonahtanjz** [comment]
Just a heads up. Since this PR involves multiple changes with organised commits, we will be using the merge commit strategy (all commit messages will be added to the master branch). Would be good to remove these "merge commits" :)

image

**Comment by jovyntls** [comment]
> Just a heads up. Since this PR involves multiple changes with organised commits, we will be using the merge commit strategy (all commit messages will be added to the master branch). Would be good to remove these "merge commits" :)

I see, thanks for the info! I'll rebase this branch on top of the master branch to avoid merge conflicts.

**Comment by jonahtanjz** [comment]
Overall looks good @jovyntls!

Just one regression:

> Navbars (breaking changes won't affect us)

Seems like the navbar in bootstrap 5 is including during printing.

image

Will need to add the [`d-print-none`](https://getbootstrap.com/docs/5.0/utilities/display/#display-in-print) class to the navbar.

**Comment by jovyntls** [comment]
Thank for the catch @jonahtanjz, I forgot about the printing :o I've made the changes!

**Comment by jovyntls** [comment]
Thank for the catch @jonahtanjz, I forgot about the printing :o I've opened #1906 to address this!

**Review by jonahtanjz — APPROVED** [review]
Nice work @jovyntls!

Overall looks good on my end. Thanks again for tackling this :)

LGTM 👍🎉

**Pull request merged**
