### PR TITLE
Support a shorter alias for <markdown> tag #136

### PR DESCRIPTION
**Pull request by rachx**
Fixes https://github.com/MarkBind/markbind/issues/136

### CODE REVIEW

**Comment by acjh** [comment]
Doesn't seem to work.

Markup:



Rendered:

**Comment by damithc** [comment]
Also, don't forget to update docs.

**Comment by rachx** [comment]
image
The first one isn't supposed to work

**Comment by acjh** [comment]
My bad, it works 👍

**Comment by acjh** [comment]
@rachx Thanks for your contribution!

**Comment by acjh** [comment]
@rachx Can you update the docs?

**Comment by rachx** [comment]
https://github.com/MarkBind/markbind-cli/wiki/Content-Authoring
Updated

**Pull request merged**
