### PR TITLE
Remove extra blank lines from page.njk output

### PR DESCRIPTION
**Pull request by ang-zeyu**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Others

**What is the rationale for this request?**
Remove extra blank lines from page.njk output

**What changes did you make? (Give an overview)**
Removed blank lines from page.njk output using nunjucks's whitespace trimming `{%-`

**Is there anything you'd like reviewers to focus on?**
na

**Testing instructions:**
`npm run test` should pass

**Proposed commit message: (wrap lines at 72 characters)**
Remove extra blank lines from page.njk output

### CODE REVIEW

**Comment by yamgent** [comment]
Thanks for this. Yes please update the expected files here, otherwise I will still have to do something like 
2ad11f5 again anyway 😛.

**Comment by ang-zeyu** [comment]
> Thanks for this. Yes please update the expected files here, otherwise I will still have to do something like
> [2ad11f5](https://github.com/MarkBind/markbind/commit/2ad11f593dbfd5329c020056d7e04e238d042b53) again anyway 😛.

By updating tests I meant doing what 2ad11f5 does exactly actually 😅 
Just to confirm, since its updated already, this pr wouldn't have any use right?

**Comment by yamgent** [comment]
> By updating tests I meant doing what [2ad11f5](https://github.com/MarkBind/markbind/commit/2ad11f593dbfd5329c020056d7e04e238d042b53) does exactly actually 😅 ( made this pr before it )

I see, I mistakenly assumed that this PR was removing additional blank lines generated by the html output. If you are interested you can rework this PR to focus on that end goal instead.

So for example, given the following html output below, the blank lines at line 22 and 25 can actually be removed, if you replace `{{` with `{{-` for the Nunjucks blocks in `page.njk`.

https://github.com/MarkBind/markbind/blob/2ad11f593dbfd5329c020056d7e04e238d042b53/test/functional/test_site_algolia_plugin/expected/index.html#L16-L29

The blank line at line 20 is also not supposed to be there, some html outputs do not have that blank line.

**Comment by ang-zeyu** [comment]
> I see, I mistakenly assumed that this PR was removing additional blank lines generated by the html output. If you are interested you can rework this PR to focus on that end goal instead.

Misunderstood your intention as well. Thanks for the suggestion!

I've updated the test files and trimmed a few more blank lines.
The commit message is also changed to reflect the purpose better.

**Comment by ang-zeyu** [comment]
Rebased on latest, no changes

**Pull request merged**
