### PR TITLE
Move preprocessThumbnails to componentParser

### LINKED ISSUE #1082: Investigate moving preprocessThumbnails to componentParser
**Is your request related to a problem?**
`preprocessThumbnails` renders the inline markdown text of thumbnail components, if any.
https://github.com/MarkBind/markbind/pull/1026#issuecomment-583320666

**Describe the solution you'd like**
It could be good if we could move this to componentParser to standardise where all such markdown parsing and rendering is done.

### PR DESCRIPTION
**Pull request by le0tan**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Enhancement to an existing feature

Resolves #1082 

**What is the rationale for this request?**

https://github.com/MarkBind/markbind/issues/1082#issue-575243900

**What changes did you make? (Give an overview)**

Move `preprocessThumbnails` to `componentParser`, following the conventions of the componentParser, I deleted the processed attributes of `<thumbnail>`

**Provide some example code that this change will affect:**

na

**Is there anything you'd like reviewers to focus on?**

na

**Testing instructions:**

`npm run test`

**Proposed commit message: (wrap lines at 72 characters)**

Let's move the preprocess logic for thumbnails to componentParser so
that the preprocessing is consistent from component to component.

### CODE REVIEW

**Comment by le0tan** [comment]
> There seems to be some image changes, don't think they are intended.

I think that's because some metadata of the pictures are changed (e.g. time of creation) and git is unable to detect such binary changes.

**Comment by ang-zeyu** [comment]
> I think that's because some metadata of the pictures are changed (e.g. time of creation) and git is unable to detect such binary changes.

Try updating on the latest

**Comment by le0tan** [comment]
> There seems to be some image changes, don't think they are intended.

@openorclose could you lift the requested changes?

**Comment by le0tan** [comment]
When merging this PR, GitHub gitched out due to the following operation sequence:

- Press "Squash and Merge" and fill out the squashed commit information
- After the "Squash and Merge", but before actually confirming the merge, another PR is squashed and merged to master
- Then confirm the merge on this PR

The result is, GitHub would prompt failur when merging the PR, but what actually happened was GitHub merged whatever in the PR into master **without squashing**.

After discussion with @nbriannl and @marvinchin we decided to keep this as the effect on the master history is minimal.

**Pull request merged**
