### PR TITLE
Remove bootstrap-vue

### PR DESCRIPTION
**Pull request by jovyntls**
**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] Others, please explain:

**Overview of changes:**
Fully removes `bootstrap-vue` from MarkBind, following #1849 and #1856/#1868.

**Anything you'd like to highlight / discuss:**
`bootstrap-vue` is still present in `packages/core/package-lock.json`; not sure if that will be an issue?

**Testing instructions:**
`bootstrap-vue` should no longer be a dependency

**Proposed commit message: (wrap lines at 72 characters)**
```
Remove bootstrap-vue

bootstrap-vue is no longer used in MarkBind as it relies on Vue 2 and
Bootstrap 4, both which we plan to upgrade. Its components have been
migrated to other libraries.

Let's remove all mentions and instances of bootstrap-vue from MarkBind
to fully remove this dependency.
```

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Comment by jonahtanjz** [comment]
> `bootstrap-vue` is still present in `packages/core/package-lock.json`; not sure if that will be an issue?

I think the `core/package-lock.json` can be removed entirely since it is not in use? Can do this in another PR :)

**Comment by ryoarmanda** [comment]
> I think the core/package-lock.json can be removed entirely since it is not in use? Can do this in another PR :)

Yeah, was just about to comment this. Looks like it was pushed into the repo not too long ago (Oct 2021). Definitely can be cleaned up.

**Review by jonahtanjz — COMMENTED** [review]
Thanks @jovyntls! Overall looks good.

Missed out on these 2 in `packages/core/test/unit/utils/data.js`:

https://github.com/jovyntls/markbind/blob/remove-bootstrap-vue/packages/core/test/unit/utils/data.js#L14

https://github.com/jovyntls/markbind/blob/remove-bootstrap-vue/packages/core/test/unit/utils/data.js#L37

**Comment by jovyntls** [comment]
> Thanks @jovyntls! Overall looks good.
> 
> Missed out on these 2 in `packages/core/test/unit/utils/data.js`:
> 
> [https://github.com/jovyntls/markbind/blob/remove-bootstrap-vue/packages/core/test/unit/utils/data.js#L14](https://github.com/jovyntls/markbind/blob/remove-bootstrap-vue/packages/core/test/unit/utils/data.js?rgh-link-date=2022-04-04T07%3A59%3A39Z#L14)
> 
> [https://github.com/jovyntls/markbind/blob/remove-bootstrap-vue/packages/core/test/unit/utils/data.js#L37](https://github.com/jovyntls/markbind/blob/remove-bootstrap-vue/packages/core/test/unit/utils/data.js?rgh-link-date=2022-04-04T07%3A59%3A39Z#L37)

Thanks for the catch! I've removed these as well now.

**Review by jonahtanjz — APPROVED** [review]
LGTM 👍

**Pull request merged**
