### PR TITLE
Add program flow page to developer guide

### LINKED ISSUE #812: Add an activity diagram to the developer guide to illustrate how MarkBind generates sites
We have a fairly complicated system right now that can be hard to understand, especially for new contributors. This will help to paint an overall picture of what exactly happens.

Might be more worthwhile to do this _after_ addressing #810

### PR DESCRIPTION
**Pull request by ang-zeyu**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Documentation update

Resolves #812
Part of #1027

**What is the rationale for this request?**
- introduce the architecture of markbind and key processes in generating sites

**What changes did you make? (Give an overview)**
- Add program flow page to developer guide with two activity diagrams illustrating the key processes
- remove outdated / redundant info in `devGuide.md`

**Proposed commit message: (wrap lines at 72 characters)**
Add program flow to developer guide

### CODE REVIEW

**Comment by ang-zeyu** [comment]
ready for review https://deploy-preview-1224--markbind-master.netlify.app/devguide/design/architecture

any thoughts? :0
@ryoarmanda @wxwxwxwx9

**Comment by wxwxwxwx9** [comment]
@ang-zeyu sorry for the late response! I have taken a look at it and compared it with the codebase. It seems pretty accurate and clear. I think it's good! At first, I was wondering if we should also include `PluginManager` but perhaps it isn't that relevant to the diagram, right? Since it isn't involved in the content processing flow.

**Comment by ang-zeyu** [comment]
thanks for the comments! @wxwxwxwx9 

I've made some changes to the diagram and added some additional snippets of info elsewhere for the points you raised:
- not too clear that content processing flow is for a single source file - added a popover 
- `<panel>`s (Externals) are separate from the content processing flow - added some tip boxes

let me know if there's anything else that can be improved here 🙂

**Comment by ryoarmanda** [comment]
Just checked the docs and the diagram looks nice! It shows a clear organization of the classes and flows, and the writeup is good for a high-level overview. Looks quite complete as well, so far most of the things I noticed first time through the codebase have been addressed 👍

**Comment by ang-zeyu** [comment]
Merged. Thanks again for the review : ) @wxwxwxwx9 @ryoarmanda

**Pull request merged**
