### PR TITLE
Update slot syntax for PageNavButton and SiteNavButton

### PR DESCRIPTION
**Pull request by wxwxwxwx9**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] Others, please explain:

This issue is related to #1078 and a follow-up to #1464. 

**Overview of changes:**
Updated the vue slot syntax for PageNavButton and SiteNavButton to the latest shorthand syntax. 

**Anything you'd like to highlight / discuss:**
NIL

**Testing instructions:**
`npm run test`

**Proposed commit message: (wrap lines at 72 characters)**
Update Vue slot syntax for PageNavButton and SiteNavButton.

PageNavButton and SiteNavButton are using deprecated Vue slot syntax. 

Let's update the syntax to the latest Vue v2.6 shorthand slot syntax. 

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No blatantly unrelated changes
- [x] Pinged someone for a review!

### CODE REVIEW

**Comment by wxwxwxwx9** [comment]
@jonahtanjz can I get your help to review this PR? Since you worked on this component, your input will be highly appreciated :-)

**Review by jonahtanjz — APPROVED** [review]
Good work 👍 The changes seem straightforward and everything appears to be working well :) Lgtm!

**Review by ang-zeyu — COMMENTED** [review]
lgtm too! 👍 let's update this one as well though : )

https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/__tests__/Navbar.spec.js

**Comment by wxwxwxwx9** [comment]
@ang-zeyu can I check if you are referring to the following?

```
const NAVBAR_CONTENT = `
<a slot="brand" href="#" title="Home" class="navbar-brand">Your Logo</a>
  <li><a href="#" class="nav-link">Topic 1</a></li>
  <li><a href="#" class="nav-link">Topic 2</a></li>
</a>
`;
```

**Comment by ang-zeyu** [comment]
yup

**Comment by wxwxwxwx9** [comment]
Hmm, I was thinking that since this is a frontend component from the user's perspective, shouldn't we retain the `slot="header"` syntax? 

[navbars](https://markbind.org/userGuide/usingComponents.html#navbars)

**Comment by ang-zeyu** [comment]
yup, however anything that 'vue sees' is already the transformed syntax you've previously implemented (i.e. this test's syntax would still be deprecated and fail if vue no longer supports `slot="..."`)

**Comment by wxwxwxwx9** [comment]
@ang-zeyu I see what you mean! Thanks for highlighting this. While working on this, I think I may have found some issues with the existing test case (I might be wrong though). 

@jonahtanjz I noticed that `<a slot="brand" href="#" title="Home" class="navbar-brand">Your Logo</a>` isn't actually inserted into the correct position :O

Currently it is inserted into the default slot along with the *Topic 1* and *Topic 2* links. 

However, I think it should have been inserted in the following section right (slot brand)?
```
<div class="navbar-brand">
      <slot name="brand"></slot>
</div>
```

Can I check if this was intended? 

I have pushed the changes that I think would be appropriate, just for easy verification purposes. If this is something to be rectified, I think we may want to do it in a new PR. But let me know if I misinterpreted something :-)

**Comment by jonahtanjz** [comment]
> Can I check if this was intended?

Nice catch @wxwxwxwx9 👍 Yup this should have been in the brand slot instead of default slot 😅

**Comment by wxwxwxwx9** [comment]
@jonahtanjz Alright! I will revert the change here. 

@ang-zeyu I think the test case won't be needing the shorthand syntax anymore, since the slot is inserted via a different format for the jest testing for Vue.

**Review by ang-zeyu — APPROVED** [review]

**Pull request merged**
