### PR TITLE
Use src instead of lib directory

### LINKED ISSUE #471: Use src instead of lib for directory structure
Taken from https://github.com/MarkBind/markbind/pull/467#issuecomment-446689914

>    As suggested with **src/plugins/render-tags.js**, let's start using **src/** instead of **lib/**.
>    
>    * **src/** is pretty common.
>    * **libs/** implies libraries' code, rather than _this_ library's code. It's more nested but clearer.
>    
>    Current directory structure:
>    ```
>    lib/
>      asset/
>      markbind/
>        lib/
>          markdown-it/
>          parser.js
>          utils.js
>        package-lock.json
>        package.json
>      template/
>      util/
>      Page.js
>      Site.js
>    package-lock.json
>    package.json
>    ```
>    Proposed directory structure:
>    ```
>    src/
>      asset/
>      lib/
>        markbind/
>          src/
>            lib/
>              markdown-it/
>            parser.js
>            utils.js
>          package-lock.json
>          package.json
>      template/
>      util/
>      Page.js
>      Site.js
>    package-lock.json
>    package.json
>    ```

### PR DESCRIPTION
**Pull request by jamos-tay**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Other, please explain: Change directory structure

Fixes #471 

**What is the rationale for this request?**

Follow up from https://github.com/MarkBind/markbind/pull/467

**What changes did you make? (Give an overview)**

Revamp directory structure to use `src` instead of lib.

### CODE REVIEW

**Comment by jamos-tay** [comment]
My bad, must've missed it

**Comment by yamgent** [comment]
As in the [original comment](https://github.com/MarkBind/markbind/pull/467#issuecomment-446689914), shouldn't it be `src/lib/markbind/...` rather than `src/markbind/...` ?

**Comment by jamos-tay** [comment]
Okay I made sure to double check it this time 😐

If possible maybe we can merge the PRs from the other guys in first, this PR will mess up their changes and I don't want to trouble them.

**Comment by yamgent** [comment]
`src/lib/markbind/package.json`: The `main:` needs to be updated to reflect the new path.

**Comment by jamos-tay** [comment]
Updated

**Comment by yamgent** [comment]
@jamos-tay Need you to resolve conflict for this PR.

**Comment by jamos-tay** [comment]
Sure, updated

**Pull request merged**
