### PR TITLE
Update Vue-Jest dev Dependency for Vue Components Package

### LINKED ISSUE #2496: Document: Node LTS (v20) and python 3.12 does not work on MarkBind install
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

M2 Mac v13.6.6

### MarkBind version

5.4.0

### Describe the bug and the steps to reproduce it

When running `npm install` in the root of markbind, see the following error:
node-gyp error

This error is caused because 3.12 python deprecates distutils, and node-gyp packaged with LTS is a node-gyp version before version 10. As stated in [this issue](https://github.com/nodejs/node-gyp/issues/2942), python 3.12 needs the newer version of node-gyp. It seems non trivial to update node-gyp version, as the [official instructions here did not work for me](https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md) (needs more testing).

However, one workaround that worked for me was adding the following line to node config 
`python=path/to/python/on/my/device` and downgrading my python version (`brew uninstall python@3.12` - though i had to force uninstall it due to dependencies)

(I also had to delete and reclone my MarkBind, but I suspect that was unrelated)

### Expected behavior

If the versions are not supported, we should maybe warn users of the problem since right now we just say the following about required version...
Screenshot 2024-04-04 at 4 34 54 PM

### Anything else?

Thank you @lhw-1 and @EltonGohJH for your extensive help troubleshooting this issue!

### PR DESCRIPTION
**Pull request by gerteck**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**

The dependency `vue-jest@3.X` is no longer supported. Let's update
to the supported vue-jest, `@vue/vue2-jest@27`

**Anything you'd like to highlight/discuss:**

When I was trying to update the node version, I faced errors installing the vue-jest dependency using Node v20, due to deasync sub-dependency, leading me to investigate.
* similar to: `https://github.com/vuejs/vue-jest/issues/403`
* `https://github.com/snowdreamtech/vue-element-admin1/issues/2`

As per https://github.com/vuejs/vue-jest,
since we are using Vue2, Jest@27, the updated package should be `@vue/vue2-jest@27`. Current dependency `vue-jest@3.X` no longer supported, prone to bugs.

image

Goal: Maintain the code, enable update of node version later on.

Opened separate PR for commit clarity. Please help to check as I'm not* entirely familiar with vue-jest as of yet, will double check again.

*Edit: Should fix #2496

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

Update vue-jest dev dependency

`vue-jest@3.X` is no longer supported. Let's update
to the supported vue-jest, `@vue/vue2-jest@27`

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [x] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Comment by gerteck** [comment]
For reference: 
* deasync is a dependency of vue-jest, which is causing an error in the setup process `npm run setup` or `npm install` while using Node v20.
* Further investigation shows vue-jest@3.X is not supported, and should be  upgraded to either vue-jest@4.X or vue/vue2-jest@27 etc. to support later versions of Node

image

image

**Comment by gerteck** [comment]
I believe it is related to #2496 as well, and should resolve the issue (needs further testing).

**Comment by Tim-Siu** [comment]
> I believe it is related to #2496 as well, and should resolve the issue (needs further testing), since it does away entirely with the problematic deasync dependency causing the issue.

I tested `npm install` in Python 3.12, Node v20 and there was no error nor warning. I think this Pull Request will solve #2496.

**Review by Tim-Siu — APPROVED** [review]
Good work on identifying and addressing this issue proactively!. Updating from `vue-jest@3.X` to `@vue/vue2-jest@27` is a important step to ensure ongoing support and compatibility with newer Node versions. This update should resolve the installation issues related to the `deasync` sub-dependency, particularly when using Node v20.

The modifications to `jest.config.js` and `package.json` are appropriate and align with the stated goals. Updating related dependencies like `@babel/preset-env` and `@vue/test-utils` helps maintain compatibility.

This change should fix issue #2496 and improve the project's ability to work with more recent Node versions.

**Pull request merged**
