### PR TITLE
Replace console.warn with logger.warn: componentParser.js

### LINKED ISSUE #1060: Importing logger from componentParser.js cause parser.test.js to fail
**Is your request related to a problem?**

In MarkBind Version: 2.11.0, I have an issue when importing logger from componentParser.js cause parser.test.js to fail.
For example, calling it accordingly as here https://github.com/MarkBind/markbind/blob/8005582e60e8f917c2629d5f81742b103133659f/src/lib/markbind/src/parsers/componentParser.js#L7

will cause `parser.test.js` to fail as shown below. 
image

As @ang-zeyu has pointed out, this occurs for parser.js as well, which is likely the reason logger isn't used in there as well.

The issue is that parser.test.js mocks the whole fs module, which causes the DailyRotateFile constructor to fail automatically in finding the directory.

**Describe the solution you'd like**

A simple fix would be to only mock the specific functions of fs relavant to parser.test.js

(Describe your proposed solution here.)

**Describe alternatives you've considered**

(Write your answer here.)

**Additional context**

(Write your answer here.)

### PR DESCRIPTION
**Pull request by nbriannl**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [ ] Documentation update
• [ ] Bug fix
• [ ] New feature
• [ ] Enhancement to an existing feature
• [X] Other, please explain: Finishing up a todo from #1057 

**What is the rationale for this request?**
This is a follow up to #1057 where `console.warn` is used instead of `logger.warn` due to a bug as raised in #1060. The test no long fail in #1117 by mocking logger in the `parser.test.js`. Although the approach could be improved.

**What changes did you make? (Give an overview)**
Replaced all `console.warn` with `logger.warn` as indicated by the TODO signposts.

**Testing instructions:**
Run tests to check if anything regressed

`markbind serve` the example code in the gist.
https://gist.github.com/nbriannl/5c44b3ee8a8af78c45a7a4f3659ce196

You should now see
image

**Proposed commit message: (wrap lines at 72 characters)**

Replace console.warn with logger.warn,

A follow up to #1057.
Let us also remove console.error as the error handler 
And directly set the error handler to be logger during init

### CODE REVIEW

**Comment by ang-zeyu** [comment]
should we fix the root cause of the tests failing first instead? ( mocking fs for `winston` )

**Comment by nbriannl** [comment]
> should we fix the root cause of the tests failing first instead? ( mocking fs for `winston` )

Even if we fix the root cause, we would still have to do this change. Therefore, I thought of doing it now. 😄 Since the bug is fixed, albeit not as ideally.

Should I raise a new issue or rewrite the issue?

**Comment by ang-zeyu** [comment]
Ahh ok, I'm fine with either. If that's the case perhaps could replace the usages in `parser.js` as well?

*edited your comment when quoting by accident

**Comment by nbriannl** [comment]
> Ahh ok, I'm fine with either. If that's the case perhaps could replace the usages in `parser.js` as well?
> 
> *edited your comment when quoting by accident

Sounds good, I can do that here.

**Comment by nbriannl** [comment]
Should i be changing this line as well? https://github.com/MarkBind/markbind/blob/68eaefb2c9bcbdd5b2708343d792df4d912cc02a/src/lib/markbind/src/parser.js#L37

**Comment by ang-zeyu** [comment]
> Should i be changing this line as well?

Yes, think we could remove it completely though, and all instances of `errorHandler` being passed as an option into the parser constructor. It was likely a workaround for the root problem

**Comment by nbriannl** [comment]
> > Should i be changing this line as well?
> 
> Yes, think we could remove it completely though, and all instances of `errorHandler` being passed as an option into the parser constructor. It was likely a workaround for the root problem

Hm, not entirely sure what you mean. `_onError` is also used in part relating to `componentPreprocessor.preProcessComponent()`

**Comment by ang-zeyu** [comment]
> Hm, not entirely sure what you mean. `_onError` is also used in part relating to `componentPreprocessor.preProcessComponent()`

It's a workaround for not being to import `logger` directly in `parser`
- when we the unit test is run, `_onError` defaults to `console.error`
- when running anything else from a user standpoint ( e.g. `markbind build` ), `errorHandler` is set to `logger.error`. Should be unncessary with the changes here now

**Pull request merged**
