### PR TITLE
Use <br> to separate lines of code block

### LINKED ISSUE #1125: Copying code in code blocks not working properly
**Tell us about your environment**

* **MarkBind Version: 2.12**

Ubuntu 18.04

**What did you do? Please include the actual source code causing the issue.**

````
line1
line2
line3
````

then `markbind serve` (or copy any of the code examples from https://markbind.org/userGuide/fullSyntaxReference.html)
**What did you expect to happen?**
When pasting into a text editor, line breaks are preserved.

**What actually happened? Please include the actual, raw output.**
```
line1line2line3
```

### LINKED ISSUE #1173: Extra unprintable chars in code blocks
When I copy-paste python code from this section, intellij indicates there are some unprintable chars.
https://nus-te3201.github.io/2020/schedule/week10/topics-py.html#appendix-d-unit-testing

image

I wonder if they have been added by MarkBind. The code in the source file doesn't seem to have the same chars. https://github.com/nus-te3201/2020/blob/te3201/programming/unittesting/text.md

### PR DESCRIPTION
**Pull request by openorclose**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Bug fix

**What is the rationale for this request?**
Fixes #1173 
Fixes #1125 

**What changes did you make? (Give an overview)**

In #991 , to handle empty lines, an unprintable character was added to make the span take up space. This causes problems for code copying.

Instead of that, let's make the span be `inline-block` and use `<br>` to put them on new lines.

**Provide some example code that this change will affect:**

````
```
some code





new lines above
```
````

This should now display correctly, and not have any new line characters inside.

**Is there anything you'd like reviewers to focus on?**
**Testing instructions:**

Check that multiple lines work, and that copying them also works

**Proposed commit message: (wrap lines at 72 characters)**

```
Use <br> and inline-block to separate spans.

Adding extra unprintable characters cause code copying to fail.

Let's not use them, and manually separate
them by using <br> instead.
```

### CODE REVIEW

**Comment by ang-zeyu** [comment]
Different fix may be needed:

code fence

https://deploy-preview-1176--markbind-master.netlify.com/userguide/formattingcontents#line-highlighting

**Comment by openorclose** [comment]
> Different fix may be needed:
> 
> code fence
> 
> https://deploy-preview-1176--markbind-master.netlify.com/userguide/formattingcontents#line-highlighting

Oh what browser is that?

I'm using firefox 73 and it looks ok:

image

**Comment by ang-zeyu** [comment]
> Oh what browser is that?

chrome v80, seems to be broken on edge ( I'm on a pretty old version though ) as well

**Comment by openorclose** [comment]
> > Oh what browser is that?
> 
> chrome v80, seems to be broken on edge ( I'm on a pretty old version though ) as well
> 
> Looks fine on firefox for me as well

Yeah, have to think of a different fix...

Changing empty lines to a single space probably wouldn't work also, since these extra spaces might affect how the program runs.

**Comment by alyip98** [comment]
@openorclose does this [fix](https://github.com/alyip98/markbind/tree/fix-copying) work?

**Comment by openorclose** [comment]
Yeah seems to work. Thanks!

**Comment by openorclose** [comment]
> OK. Just a non-blocking question, can't remember whether this was asked: why did we use `<span>` instead of `<div>`?

I chose it rather arbitrarily, but if i were to give a reason it would be that `<span>` can only contain inline elements which seems more appropriate for showing a line of code.

**Comment by jamessspanggg** [comment]
@openorclose code copying for safari:

Kapture 2020-04-10 at 23 33 06

**Pull request merged**
