### PR TITLE
[Do not merge] Trial disable write siteData on each page build

### PR DESCRIPTION
**Pull request by ryoarmanda**
Again, **do not merge**.

**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [x] Others, please explain:

A PR to help identify root cause of #1619 

**Overview of changes:**

**Anything you'd like to highlight / discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No blatantly unrelated changes
- [ ] Pinged someone for a review!

### CODE REVIEW

**Comment by damithc** [comment]
@ryoarmanda I'm moving the discussion here, as it is specific to the PR.

Even after running `npm run setup`, I still have to run `npm link` or else it will not pick up the dev version of the code. I still get that error from `npm link` but ignored it this time as the dev version seems to be linked even if there was an error.

Here's the error message from `markbind serve -o -b`.
> v3.0.4-trial
info: Website generation (lazy) started at 6:23:30 pm
info: Building assets...
info: Assets built
info: Generating landing page...
info: Landing page built, other pages will be built as you navigate to them!
info: Site data built
info: Website generation (lazy) complete! Total build time: 10.242s
info: Serving "C:\repos\nus-cs2103\cs2103-website-base\_site" at http://127.0.0.1:8080
info: Press CTRL+C to stop ...
info: Building files that are not viewed in the background...
warn:  message=UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json', stack=Error: UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json', errno=-4094, code=UNKNOWN, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json
error: Failed to copy asset markbind-plugin-anchors.css for plugin markbind-plugin-anchors
Error: ENOENT: no such file or directory, mkdir 'C:\repos\nus-cs2103\cs2103-website-base\_site\plugins\markbind-plugin-anchors'
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24), errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat._include_.html
Unhandled rejection Error: Error while generating undefined
    at C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Site\index.js:1175:18
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\brooksLaw\index.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\brooksLaw\index.html', errno=-4058, code=ENOENT, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\brooksLaw\index.html
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:288:18)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Page.collectHeadingsAndKeywords (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:232:10)
    at Page.generate (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:489:10)
    at async C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Site\index.js:1167:11, errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Page.collectHeadingsAndKeywords (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:232:10)
    at Page.generate (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:489:10), errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html

**Comment by ang-zeyu** [comment]
Thanks for taking a look at this @ryoarmanda 

If it helps, the area flagged by the original error message (line 277 in `Page`) has been heavily plagued by race conditions.

I took a brief look through the background build code again but nothing immediately alarming jumps out. 

```
warn: message=UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base_site\siteData.json', stack=Error: UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base_site\siteData.json', errno=-4094, code=UNKNOWN, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base_site\siteData.json
error: message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat.include.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat.include.html'
at Object.openSync (fs.js:498:3)
at Object.readFileSync (fs.js:394:35)
at Object. (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules@markbind\core\src\Page\index.js:277:37)
at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules@markbind\core\src\Page\index.js:254:8)
```

---

But my guess (haven't encountered this problem either) is that this implementation is causing the issue

```
stopOngoingBuilds() {
  this.stopGenerationTimeThreshold = new Date();
}
```

Relying on a `stopGenerationTimeThreshold` would not immediately stop all prior page generation necessarily before the new batch begins, especially on slower machines.

e.g.
```
// suppose we have 3 pages 1 2 3

1. page1.generate() is called
2. background build is retriggered
3. pages 2 and 3 are prevented by stopGenerationTimeThreshold from generating, but, page1 is still generating
4. while page1 is still generating, the new batch of pages begins generating as well
5. page1 messes with the new batch of pages' generation (resulting in the above missing file error)
```

*just a guess though, haven't really checked it out.


also a little off-topic but that error causing area in `Page` really needs some rework https://github.com/MarkBind/markbind/issues/1495 🌚 (might be a solution to this maybe)

**Comment by ryoarmanda** [comment]
Thanks for the ideas @ang-zeyu, looks like this is a hard problem to debug.

Your `stopGenerationTimeThreshold` idea makes sense (and reveals a possible issue with the current way of stopping background builds), but Prof has reported that the errors can be reliably produced without any user control. So the error can happen within the original (and the only) background-build job. Nevertheless, the stop mechanism is certainly a piece of procedure to look again though, thanks for bringing that up.

---

My guess on the cause is from overwhelming requests to write to `siteData.json`. I worked backwards from the error logs, observing where that particular error/warn can be produced, and what can cause that to happen. And I roughly got the big picture, yet still untested. I did a short summary on my findings in the issue page. But essentially, what I think happens is:

1. Overwhelming number of requests to write to `siteData.json` in the `writeSiteData` method causes some fs error. The error handling in that method calls the utility `rejectHandler` method with that error, the output path (`_site/`), and the temp path.
2. In `rejectHandler`, it will first output a `warn` of the error. After that, it will remove all the given paths, which causes all files in `_site/` to be gone, files that the currently-running `Page.generate`s need.
3. `Page.generate`s will return error and the error-handling in each callback logs the `error` and rejects. However, the rejection is not handled in `runPageGenerationTasks`, which causes the `unhandled rejection error` and crashes (oops)

This will explain pretty much the entire log dump. But I feel it's pretty circumstantial, so I want to check if this is the case. I think I will try to just throw a dummy error in `writeSiteData` and see if the log output would match.

---

What I'm even more confused now is that, even though the log posted earlier by @damithc has `v3.0.4-trial`, the errors are not consistent with the trial PR, particularly the unhandled rejection error. Notice the stack trace of that error, it says `Site/index.js:1175:18`, presumably the position of the error of the rejection. If you check the file out in this trial PR, line 1175 is just a closing brace. In fact, `1175:18` is exactly the position of the `reject` call error in master. That unhandled rejection error message is an issue as well. Also, a fix in the trial PR will actually handle the rejection if it happens. This suggests that the trial PR fix did not come through...

I'm actually not sure how the inconsistency can happen, any thoughts?

**Comment by damithc** [comment]
> I'm actually not sure how the inconsistency can happen, any thoughts?

Could be due to the error I encountered during `npm link`. Perhaps the linking was only partial?

>$ npm link
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\live-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>
>moved 8 packages and audited 851 packages in 7.222s
>
>28 packages are looking for funding
  run `npm fund` for details
>
>found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm ERR! code EEXIST
npm ERR! path C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\index.js
npm ERR! dest C:\Users\dcsdcr\AppData\Roaming\npm\markbind
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\index.js' -> 'C:\Users\dcsdcr\AppData\Roaming\npm\markbind'
npm ERR! File exists: C:\Users\dcsdcr\AppData\Roaming\npm\markbind
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dcsdcr\AppData\Roaming\npm-cache\_logs\2021-07-08T16_04_03_722Z-debug.log

But if is use the `--force` option as suggested by the error message, this happens:

>$ markbind serve -o
>error: uncaughtException: Cannot find module 'send'
>Require stack:
> - C:\repos\markbind\markbind\packages\cli\src\lib\live-server\index.js
> - C:\repos\markbind\markbind\packages\cli\index.js date=Fri Jul 09 2021 00:07:08 GMT+0800 (Singapore Standard Time), pid=26904, uid=null, gid=null, cwd=C:\repos\nus-cs2103\cs2103-website-base, execPath=C:\Program Files\nodejs\node.exe, version=v14.17.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\index.js, serve, -o], rss=77357056, heapTotal=60731392, heapUsed=41303328, external=2827408, arrayBuffers=1300396, loadavg=[0, 0, 0], uptime=11785
> Error: Cannot find module 'send'
> Require stack:
> - C:\repos\markbind\markbind\packages\cli\src\lib\live-server\index.js
> - C:\repos\markbind\markbind\packages\cli\index.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
>     at Module.require (internal/modules/cjs/loader.js:957:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\src\lib\live-server\index.js:26:10)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
>     at Module.require (internal/modules/cjs/loader.js:957:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\index.js:23:20)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)

**Comment by ryoarmanda** [comment]
> I think I will try to just throw a dummy error in writeSiteData and see if the log output would match

Just tried this and I got a close output with the log provided.

Replication (from master branch):
1. Go to `writeSiteData` in `Site/index.js`, inside the `try` block, add `throw new Error('Dummy error from writeSiteData');` just before `await fs.outputJson(...);`
2. Run `markbind serve -o -b` in the cs2103 website project folder
3. Wait as background build goes on, it will have a ton of `warn`s of the dummy error (expected), but along the line you will see this:

```
warn:  message=Dummy error from writeSiteData, stack=Error: Dummy error from writeSiteData
    at Site.writeSiteData (C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Site\index.js:1433:15)
    at C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Site\index.js:1170:24
error:  message=ENOENT: no such file or directory, open 'C:\Users\Ryo Armanda\projects\website\_site\book\uml\notes\notes\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\Users\Ryo Armanda\projects\website\_site\book\uml\notes\notes\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\Users\Ryo Armanda\projects\markbind\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Page\index.js:254:8)
    at Page.collectHeadingsAndKeywords (C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Page\index.js:232:10)
    at Page.generate (C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Page\index.js:489:10)
    at async C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Site\index.js:1167:11, errno=-4058, syscall=open, code=ENOENT, path=C:\Users\Ryo Armanda\projects\website\_site\book\uml\notes\notes\unit-inElsewhere-asFlat._include_.html
Unhandled rejection Error: Error while generating undefined
    at C:\Users\Ryo Armanda\projects\markbind\packages\core\src\Site\index.js:1175:18
```

The output corresponds the sequence of logs provided. Interestingly, this won't crash in my machine, though after enough errors of the same type (a total of 4 occurrences), it will just do nothing (might look like MarkBind freezes).

However, even though it looks promising, I'm not sure if this is the same case as Prof experienced.

**Pull request closed without merging**
