### PR TITLE
Introducing Custom Markdown Syntax Pipeline and QR Code Component

### PR DESCRIPTION
**Pull request by SPWwj**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [X] Feature addition or enhancement
- [X] Code maintenance
- [ ] DevOps
- [X] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Code:
```
[qrcode: data="Markbind QR Code" ]
```

Output:
image

Code:
```
[qrcode: data="Night Sky" size="10" ec_level="H" fill='rgba(0, 0, 0, 1)' backgroundColor="rgba(0, 0, 0, 0)" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="0.05" image="4.png" imageOpacity="0.5"]
```
Output:
image

Code:
```
[qrcode: data="All Blue" size="10" ec_level="H" fill='rgba(0, 0, 0, 1)' backgroundColor="rgba(0, 0, 0, 0)" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="0.05" image="2.png" imageOpacity="0.8"]

```
Output:
image

Code:
```
[qrcode: data="BBQ" size="11" ec_level="H" fill='rgba(0, 0, 0, 0.5)' backgroundColor="rgba(0, 0, 0, 0)" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="0.2" image="3.png" imageOpacity="0.9"]
```
Output:
image

**Anything you'd like to highlight/discuss:**
This PR introduces a <kbd>**custom markdown syntax pipeline**</kbd>, enabling developers to create unique markdown inline elements. For instance, you can define syntax like:
```
[qrcode: data="BBQ"]
@@trigger:@@
<graphNode: data="Node 1">

```

With this pipeline, you can create your own custom inline elements like:
```
markdownIt.use(require('markdown-it-mark'))
  .use(customTagPlugin, {
    name: 'qrcode',
    startDelimiter: '[',
    endDelimiter: ']',
    component: QrCodeComponent.render,
  });
```

For detailed examples, please refer to this PR.

**Testing instructions:**

# Custom Parameters

Below are the descriptions of the customizable parameters:

- `stroke`: The color of the stroke. It accepts a color in any valid CSS format.

- `stroke-linecap`: The style of the ending of lines in shapes, other than rectangles. Valid values include `butt`, `round` and `square`.

- `stroke-linejoin`: The shape of the corner where two lines meet. Valid values include `miter`, `round` and `bevel`.

- `fill`: The color to fill the QR code. It accepts a color in any valid CSS format.

- `stroke-width`: The width of the stroke.

- `backgroundColor`: The background color of the QR code. It accepts a color in any valid CSS format.

- `image`: If specified, an image will be displayed at the center of the QR code. It accepts a URL of the image.

- `imageOpacity`: The opacity of the image displayed at the center of the QR code. It accepts a number between 0 and 1.

- `data`: The information to be encoded in the QR code.

- `size`: The size of the QR code. The larger the size, the bigger the QR code.

- `ec_level`: Error correction level of the QR code. The higher the error correction level, the more resilient the QR code is to damage. Valid values include `L` (low), `M` (medium), `Q` (quartile), and `H` (high).

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

**Comment by damithc** [comment]
@SPWwj I don't think we'll be adding a QR code feature to MarkBind, as it is not a good fit for our target users. You can be credited with the work done though.
In future, it's best to discuss with us first before implementing a new feature.

**Comment by SPWwj** [comment]
> @SPWwj I don't think we'll be adding a QR code feature to MarkBind, as it is not a good fit for our target users. You can be credited with the work done though. In future, it's best to discuss with us first before implementing a new feature.

Understood. Primarily, I aim to demonstrate the Custom Markdown Syntax Pipeline. Currently, Markbind lacks a streamlined method for declaring additional markdown syntax components. These components are mostly in HTML tags, rendered by Vue. It would be beneficial to define markdown-like syntax unsupported by the original markdown code. The QR code is merely a handy tool.

**Comment by ang-zeyu** [comment]
> Currently, Markbind lacks a streamlined method for declaring additional markdown syntax components. These components are mostly in HTML tags, rendered by Vue. It would be beneficial to define markdown-like syntax unsupported by the original markdown code.

Agreed its not ideal. The other side is that we have a lot of HTML syntax https://markbind.org/userGuide/usingComponents.html unfortunately since day one. It'd be extremely difficult to both either:
- Come up with a unique, non-interfering markdown syntax for every tag/feature
- Or guide UX (author) expectations on what should and should not be a HTML tag (we do not have such a guideline)

Do you have a specific example in mind you want to make more user friendly with Markdown specifically? We can discuss that in more detail and maybe improve the author UX in another issue if so too.

> streamlined

:eyes: Not too sure what's meant by this though. Isn't this a markdown plugin?

I am thinking something like https://github.com/rlidwka/markdown-it-regexp when you say "streamlined".

**Comment by SPWwj** [comment]
> I aomething like https://github.com/rlidwka/markdown-it-regexp when you say "streamlined".

It is the NodeProcessor.ts pipeline that processes markdown components. However, the current system provides an overly complex array of methods for adding new components.

image

The complexity of the current system makes it hard for maintainers to locate the code. Moreover, introducing the Vue component allows developers to bypass this pipeline, leading to a possibility that not all components are included in the pipeline. Therefore, there's significant room for improvement.

 ## Possible suggestion ##
Possible suggestion for the pipeline can be something this where you can see all the components and syntax at one glance:
```
markdownIt.use(require('markdown-it-mark'))
  .use(customTagPlugin, {
    name: 'qrcode',
    startDelimiter: '[',
    endDelimiter: ']',
    component: QrCodeComponent.render,
  }).use(customTagPlugin, {
    name: 'thumbnail',
    startDelimiter: '[',
    endDelimiter: ']',
    component: Thumbnail.render,
  }).use(customTagPlugin, {
    name: 'Box',
    startDelimiter: '[',
    endDelimiter: ']',
    component: BoxComponent.render,
    block: true
  }).use(customTagPlugin, {
    name: 'Header',
    startDelimiter: '[',
    endDelimiter: ']',
    component: HeaderComponent.render,
    block: true,
    pipeline: 'post'
  }).use(customTagPlugin, {
    name: 'Theme',
    component: ThemeComponent.render,
  }).use(customTagPlugin, {
    name: 'Attrs',
    component: AttrsComponent.render,
    pipeline:'pre'
  });
```

 For example:

image

Thus the issue like this will never happen(I passed my typescript syntax check but fail at auto generated js syntax 😂):
image


## Mixing of html and markdown is buggy:

Consider the screenshot below, this fail for me unexpectedly 😂
image

Additionally, no existing formatter supports the integration of HTML and markdown code. Therefore, converting all HTML components to markdown syntax could significantly simplify our process. This would allow us to utilize existing formatters without encountering any issues.

## To much abstraction is not good for md

In my perspective, I view markdown as an intermediary tool bridging the gap between the user interface and HTML code. Let's take this list as an example:

image

This is significantly more straightforward compared to the corresponding HTML code:

image

Thus, content creators without prior knowledge of HTML, JS, and CSS can easily utilize this to create presentations and websites, perhaps even with the aid of AI now.

Thus something like like should be avoid:
image

However, implementing simple, understandable encapsulations such as pagination is essential, even for those without programming knowledge.

Therefore, complex layouts like the following might be too intricate and should predominantly be managed by our compiler.

```
<head-bottom>
  <link rel="stylesheet" href="{{baseUrl}}/stylesheets/main.css">
</head-bottom>

<header sticky>
  <navbar type="dark">
    <a slot="brand" href="{{baseUrl}}/index.html" title="Home" class="navbar-brand">Your Logo</a>
    <li><a href="{{baseUrl}}/contents/topic1.html" class="nav-link">Topic 1</a></li>
    <li><a href="{{baseUrl}}/contents/topic2.html" class="nav-link">Topic 2</a></li>
    <dropdown header="Topic 3" class="nav-link">
      <li><a href="{{baseUrl}}/contents/topic3a.html" class="dropdown-item">Topic 3a</a></li>
      <li><a href="{{baseUrl}}/contents/topic3b.html" class="dropdown-item">Topic 3b</a></li>
    </dropdown>
    <li slot="right">
      <form class="navbar-form">
        <searchbar :data="searchData" placeholder="Search" :on-hit="searchCallback" menu-align-right></searchbar>
      </form>
    </li>
  </navbar>
</header>

<div id="flex-body">
  <nav id="site-nav">
    <div class="site-nav-top">
      <div class="fw-bold mb-2" style="font-size: 1.25rem;">Contents</div>
    </div>
    <div class="nav-component slim-scroll">
      <site-nav>
* [Home :house:]({{ baseUrl }}/index.html)
* [Topic 1]({{baseUrl}}/contents/topic1.html)
* [Topic 2]({{baseUrl}}/contents/topic2.html)
* Topic 3 :expanded:
  * [Topic 3a]({{baseUrl}}/contents/topic3a.html)
  * [Topic 3b]({{baseUrl}}/contents/topic3b.html)
      </site-nav>
    </div>
  </nav>
  <div id="content-wrapper">
    <breadcrumb />
    {{ content }}
  </div>
  <nav id="page-nav">
    <div class="nav-component slim-scroll">
      <page-nav />
    </div>
  </nav>
  <scroll-top-button></scroll-top-button>
</div>

<footer>
  <!-- Support MarkBind by including a link to us on your landing page! -->
  <div class="text-center">
    <small>[Generated by {{MarkBind}}]</small>
  </div>
</footer>
```


Consider something like this:

```
* index
* about
* contact

{nav}

@page "index.html" {title ="index"}

@page footer
```

I understand that this idea might be disruptive and potentially unsuitable for MarkBind. However, it's a concept that has been on my mind and I welcome any discussion on it.

**Comment by ang-zeyu** [comment]
1. **Rewriting existing HTML components using markdown.**

It's an interesting idea. Imo,

Pros of Markdown:
- Can be terser and more user friendly

Cons:
- Loss of leveraging familiarity, as HTML is fairly commonly known. Too much varied custom syntax can prove to be not very user friendly.

Based on these 2 points alone, I don't really have a preference for one the other, but:

One more con:
- Humongous, humongous, humongous amounts of work to rewrite everything. This would be the main reason I personally would not change things, and its **not product related**. Components have been there since MarkBind day 1. I (and most here) would likely not have the time to supervise the effort but I'd be happy to give permissions if you are keen on taking this on. 💪 

(also why I asked this)

> Do you have a specific example in mind you want to make more user friendly with Markdown specifically? We can discuss that in more detail and maybe improve the author UX in another issue if so too.

ping @damithc for opinion

2. **This comment**

> The complexity of the current system makes it hard for maintainers to locate the code. Moreover, introducing the Vue component allows developers to bypass this pipeline, leading to a possibility that not all components are included in the pipeline. Therefore, there's significant room for improvement.

Agreed with consolidating related functionality into one place.

What do you think of adding an API to `Plugin` to allow configuring markdown additions? 

This should allow rewriting a lot of components that are spread out into one file. (e.g. code blocks)

https://markbind.org/devdocs/devGuide/development/writingPlugins.html

3. **This comment**

> Consider the screenshot below, this fail for me unexpectedly 😂

Some context:

We [patched](https://github.com/MarkBind/markbind/tree/master/packages/core/src/lib/markdown-it/patches/custom-component) markdown-it (some parts of it adapted from Vuepress) to allow adding additional tags that are parsed the same way the markdown spec treats `<script/style>`, because we want the content in some of these tags (e.g. `<include>`) to be extracted and processed as-is. (there is also a HTMLparser patch to parse it like script/style tags too)

While "spec compliant" and easier to implement (main reason it was done so), I agree it is not user friendly, parsing it in the way you shown your example would be best. You might have realized this based on your other recent work on markdown this is really not easy to implement, let alone define consistently without breaking the existing spec/behaviours. You could try participating in/investigating in Commonmark forums for a start if you'd really like to understand this specific design choice (needing a blank line for `script/style/pre`).

Until then:

Imo the best path here is to work on any documentation holes and inconsistencies, and document these behaviours clearly. And/Or consider switching to markdown based syntaxes per your first point.

4. **This comment**

> Thus the issue like this will never happen(I passed my typescript syntax check but fail at auto generated js syntax 😂):

This is unrelated, we currently haven't completely migrated to typescript yet (I think), and are manually allowlisting `.js` files in `eslintignore`.

https://github.com/MarkBind/markbind/issues/1913

https://markbind.org/devdocs/devGuide/development/migratingToTypeScript.html

Once everything is done we can "flip the ignore" (ignore all js files except certain ones) to remove this issue. We might already be at the point we can do the flip (I haven't been keeping track here much).

5. **This comment**

> Additionally, no existing formatter supports the integration of HTML and markdown code. Therefore, converting all HTML components to markdown syntax could significantly simplify our process. This would allow us to utilize existing formatters without encountering any issues.

Not too sure on this, isn't this (and anything else we add)

```
    startDelimiter: '[',
    endDelimiter: ']',
```

an *extension*? (formatters would not recognise it either)

6. **This comment**

> Therefore, complex layouts like the following might be too intricate and should predominantly be managed by our compiler.

Agreed on the general feel it is too intricate.

There's an open issue for simplifying the `<navbar>` syntax specifically https://github.com/MarkBind/markbind/issues/2079

For layouts, https://github.com/MarkBind/markbind/issues/2077

7. **This image**

> image

Can this not be achieved via `<include>`?

**Comment by damithc** [comment]
> ping @damithc for opinion

Yes, we need to consider cost/benefit, and we can't afford to take on big redesign jobs as we don't have lot of manpower available. One way we can tackle such major 'experimental' work is to do it as a final year project. So, if someone is willing to take on such a big task, they can do it as an FYP, and evaluate the cost-benefit as part of the project. That way, the person still gets an FYP out of it even if we don't actually merge the new design.

**Pull request closed without merging**
