### PR TITLE
Force cheerio to use MarkBind's htmlparser2

### LINKED ISSUE #582: Force cheerio to use our own custom htmlparser2
Occurs when using node v8.15.0 (which bundles npm v6.4.1).

When setting up the repo for the first time and using `npm install`, npm will install cheerio, one of our dependencies. cheerio in turn is dependent on htmlparser2.

Due to issues with the way [the original htmlparser2 parses the angular brackets](https://github.com/MarkBind/markbind/issues/101), we had to fork our [own custom version of htmlparser2](https://github.com/MarkBind/htmlparser2) in order to fix the issue.

When running `npm install` under npm v6.4.1, npm would not use our custom htmlparser2, but uses the one by the official version. This will cause an error for MarkBind v1.16.0 (provided by @Xenonym):

```
PS C:\Users\pzy5a\Documents\GitHub\markbind\docs> markbind build
  __  __                  _      ____    _               _
 |  \/  |   __ _   _ __  | | __ | __ )  (_)  _ __     __| |
 | |\/| |  / _` | | '__| | |/ / |  _ \  | | | '_ \   / _` |
 | |  | | | (_| | | |    |   <  | |_) | | | | | | | | (_| |
 |_|  |_|  \__,_| |_|    |_|\_\ |____/  |_| |_| |_|  \__,_|
 v1.16.0
info: Website generation started at 1:54:34 AM
info: Building assets...
info: Assets built
info: Generating pages...
[------------------] 0 / 18 pages builterror: TypeError: Cannot set property 'src' of null
warning: Error: Error while generating C:\Users\pzy5a\Documents\GitHub\markbind\docs\userGuide\makingTheSiteSearchable.md
error: Error: Empty src attribute in include in: C:\Users\pzy5a\Documents\GitHub\markbind\docs\userGuide\reusingContents.md
error: TypeError: Cannot set property 'src' of null
[================--] 16 / 18 pages builtwarning: Error: Error while generating C:\Users\pzy5a\Documents\GitHub\markbind\docs\userGuide\makingTheSiteSearchable.md
error: Error while generating C:\Users\pzy5a\Documents\GitHub\markbind\docs\userGuide\makingTheSiteSearchable.md
```

Solution: Use `npm shrinkwrap` to force cheerio to use our own version of htmlparser2.

Temporary workaround: If you face this issue, discard the changes made by npm for `package-lock.json`, and redo `npm install`.

----

Additional info: `package-lock-new.json` is the one whereby cheerio uses the official version of htmlparser2.

```diff
diff --git a/package-lock.json b/package-lock-new.json
index 5856b37..8c5a77d 100644
--- a/package-lock.json
+++ b/package-lock-new.json
@@ -828,6 +828,39 @@
         "lodash.reduce": "^4.4.0",
         "lodash.reject": "^4.4.0",
         "lodash.some": "^4.4.0"
+      },
+      "dependencies": {
+        "htmlparser2": {
+          "version": "3.10.0",
+          "resolved": "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.10.0.tgz",
+          "integrity": "sha512-J1nEUGv+MkXS0weHNWVKJJ+UrLfePxRWpN3C9bEi9fLxL2+ggW94DQvgYVXsaT30PGwYRIZKNZXuyMhp3Di4bQ==",
+          "requires": {
+            "domelementtype": "^1.3.0",
+            "domhandler": "^2.3.0",
+            "domutils": "^1.5.1",
+            "entities": "^1.1.1",
+            "inherits": "^2.0.1",
+            "readable-stream": "^3.0.6"
+          }
+        },
+        "readable-stream": {
+          "version": "3.1.1",
+          "resolved": "https://registry.npmjs.org/readable-stream/-/readable-stream-3.1.1.tgz",
+          "integrity": "sha512-DkN66hPyqDhnIQ6Jcsvx9bFjhw214O4poMBcIMgPVpQvNy9a0e0Uhg5SqySyDKAmUlwt8LonTBz1ezOnM8pUdA==",
+          "requires": {
+            "inherits": "^2.0.3",
+            "string_decoder": "^1.1.1",
+            "util-deprecate": "^1.0.1"
+          }
+        },
+        "string_decoder": {
+          "version": "1.2.0",
+          "resolved": "https://registry.npmjs.org/string_decoder/-/string_decoder-1.2.0.tgz",
+          "integrity": "sha512-6YqyX6ZWEYguAxgZzHGL7SsCeGx3V2TtOTqZz1xSTSWnqsbWwbptafNyvf/ACquZUXV3DANr5BDIwNYe1mN42w==",
+          "requires": {
+            "safe-buffer": "~5.1.0"
+          }
+        }
       }
     },
     "chokidar": {
@@ -2332,6 +2365,7 @@
         "combined-stream": {
           "version": "1.0.5",
           "bundled": true,
+          "optional": true,
           "requires": {
             "delayed-stream": "~1.0.0"
           }
@@ -2386,7 +2420,8 @@
         },
         "delayed-stream": {
           "version": "1.0.0",
-          "bundled": true
+          "bundled": true,
+          "optional": true
         },
         "delegates": {
           "version": "1.0.0",
@@ -2633,11 +2668,13 @@
         },
         "mime-db": {
           "version": "1.27.0",
-          "bundled": true
+          "bundled": true,
+          "optional": true
         },
         "mime-types": {
           "version": "2.1.15",
           "bundled": true,
+          "optional": true,
           "requires": {
             "mime-db": "1.27.0"
           }
@@ -2703,7 +2740,8 @@
         },
         "number-is-nan": {
           "version": "1.0.1",
-          "bundled": true
+          "bundled": true,
+          "optional": true
         },
         "oauth-sign": {
           "version": "0.8.2",
```

### PR DESCRIPTION
**Pull request by acjh**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [ ] Documentation update
• [ ] Bug fix
• [ ] New feature
• [ ] Enhancement to an existing feature
• [x] Other, please explain:

Use npm-shrinkwrap.json to ensure that developers and users of MarkBind will use cheerio with MarkBind's htmlparser2. npm-shrinkwrap.json is published to npm for users that install from npm.

Fixes #582

**What is the rationale for this request?**

Fresh installs of npm before this change may install htmlparser2 v3.10.0.
This happens on Netlify too.

This is suspected to be due to one or both of these reasons:
- cheerio specifies `"htmlparser2": "^3.9.1"` and 3.10.0-markbind.1 < 3.10.0 (https://semver.org).
- MarkBind's htmlparser2 is based off 3.9.2 and 3.9.2 < 3.10.0.

However, [fb55/htmlparser2](https://github.com/fb55/htmlparser2) published v3.10.0 in October 2018 and we only encounter this now.

**What changes did you make? (Give an overview)**

```diff
    "cheerio": {
      "version": "0.22.0",
      "resolved": "https://registry.npmjs.org/cheerio/-/cheerio-0.22.0.tgz",
      "integrity": "sha1-qbqoYKP5tZWmuBsahocxIe06Jp4=",
      "requires": {
        ...
+     },
+     "dependencies": {
+       "htmlparser2": {
+        "version": "3.9.2",
+         "resolved": "github:MarkBind/htmlparser2#815b507c5268a178fa24741d6f74fcc0bc9be4cd",
+         "requires": {
+           "domelementtype": "^1.3.0",
+           "domhandler": "^2.3.0",
+           "domutils": "^1.5.1",
+           "entities": "^1.1.1",
+           "inherits": "^2.0.1",
+           "readable-stream": "^2.0.2"
+         }
+       }
      }
```

**Provide some example code that this change will affect:**

\-

**Is there anything you'd like reviewers to focus on?**

Is this a good way? We will need to update npm-shrinkwrap.json whenever we update htmlparser2.

**Testing instructions:**

```shell
$ rm -rf node_modules/
$ npm i
```

### CODE REVIEW

**Comment by acjh** [comment]
I can reproduce the error by using [`npm ci`](https://docs.npmjs.com/cli/ci.html) like Travis does, instead of `npm i`.
However, I cannot seem to pinpoint which dependencies are installed differently.
Commenting out `node_modules` in `.gitignore` and staging the folder shows no diff.

**Comment by acjh** [comment]
There is diff in `node_modules/htmlparser2/package.json`, but I haven't figured out what's wrong.

**Comment by acjh** [comment]
That diff turned out to be fine.

I found that `npm ci` still installs htmlparser2 v3.9.2 for cheerio by doing this in `.gitignore`:
```diff
- node_modules
+ node_modules/*
+ !node_modules/cheerio
+ !node_modules/htmlparser2
```

And then looking for the changes from https://github.com/MarkBind/htmlparser2/pull/1/files.

Since `npm ci` doesn't modify lock files, I tried to see if changing this line in `npm-shrinkwrap.json` (which `npm i` converts into the diff mentioned in the PR description)  would work — but it doesn't:
```diff
    "cheerio": {
      "version": "0.22.0",
      "resolved": "https://registry.npmjs.org/cheerio/-/cheerio-0.22.0.tgz",
      "integrity": "sha1-qbqoYKP5tZWmuBsahocxIe06Jp4=",
      "requires": {
        ...
-       "htmlparser2": "^3.9.1",
+       "htmlparser2": "github:MarkBind/htmlparser2#v3.10.0-markbind.1",
```

Although `npm i` works, (the current changes in) `npm-shrinkwrap.json` is not a complete solution.

**Comment by yamgent** [comment]
This is the only idea I have right now to resolve the problem:

1. Fork cheerio, modify their `package.json` to use MarkBind's htmlparser2. 
2. Update MarkBind's `package.json` to use our forked version of cheerio.
2. Upgrade our own htmlparser2 to 3.10.0, and reapplying the changes that we did on our side. This is so that we do not break the new features in htmlparser2 that cheerio might be using.

**Comment by acjh** [comment]
Yes, I get some failed tests in `npm test`.

I also noticed we use `cheerio.html`, which is different from `$.html` and undocumented, in several places.

**Comment by yamgent** [comment]
Tried it on my side, the new cheerio does not support setting default options so I temporary duplicated the settings on every cheerio calls in order to fix the unit tests. The branch with the new cheerio is in here:

https://github.com/yamgent/markbind/tree/use-cheerio-1.0.0-rc.2

The only test that is failing for the above branch is for test_site, due to the addition of the `<html>` wrapping, which leads to this part:

> I also noticed we use `cheerio.html`, which is different from `$.html` and undocumented, in several places.

The new cheerio generates a different output for `.html()`. According to this issue https://github.com/cheeriojs/cheerio/issues/1031, the changes seem to be intended.

So for the code below:

```javascript
const cheerio = require('cheerio')
const $ = cheerio.load('<h2 class="title">Hello world</h2>')

$('h2.title').text('Hello there!')
$('h2').addClass('welcome')

$.html()
```

cheerio@0.22.0's output:

```html
<h2 class="title welcome">Hello there!</h2>
```

cheerio@1.0.0-rc.2's output:
```html
<html><head></head><body><h2 class="title welcome">Hello there!</h2></body></html>
```

**Comment by acjh** [comment]
Passing options will use htmlparser2, which we do not want.

**Comment by yamgent** [comment]
> Passing options will use htmlparser2, which we do not want.

Oh? I wasn't aware of that, I am out of ideas for this front then :X.

**Pull request closed without merging**
