### PR TITLE
Fix imported modal button position off

### LINKED ISSUE #2473: Modals: The x button position is off
The `X` seems too close to the edge?

image

### PR DESCRIPTION
**Pull request by yiwen101**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Fixes #2473 
Credit to @tlylt for all the work and investigation; the actual fix code is trivial.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**
test with `markbind serve -d`

**Proposed commit message: (wrap lines at 72 characters)**
Fix off-positioned close button in imported modal

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [x] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Comment by yucheng11122017** [comment]
Hi @yiwen101 I think you shouldn;t be commiting the changes in the binary files

**Comment by yiwen101** [comment]
> Hi @yiwen101 I think you shouldn;t be commiting the changes in the binary files

Thanks, will revert the result of npm run build:web

**Comment by yiwen101** [comment]
> Could you add a functional test for testing the behaviour described in the issue? If you can do a unit test, would be even better but might be a bit tough

Sorry for the late reply. I have added the functional test.
To verify the result of fix, remember to do "markbind serve -d", otherwise the position will still be off(since frontend is updated per release).

**Review by EltonGohJH — APPROVED** [review]
LGTM!

The language for commit message seems off.
how bout `Fix off-positioned button in imported modal`

**Comment by yiwen101** [comment]
> LGTM!
> 
> The language for commit message seems off. how bout `Fix off-positioned close button in imported modal`

Thanks for the review and suggestions on the commitment message. Yes, the suggested commit message is clearer. I have also updated the "proposed commit message" for this PR accordingly.

**Review by itsyme — APPROVED** [review]
LGTM! Thanks for the effort to write the functional tests as well!

**Pull request merged**
