### PR TITLE
Migrate layout to Typescript

### PR DESCRIPTION
**Pull request by yiwen101**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [x] DevOps
- [x] Improve developer experience
- [ ] Others, please explain:

work on #1913. Credit to #2164 for some of the works. Did not commit to #2164 to avoid the git rebase issues currently haunting it.

**Overview of changes:**
Update the use of layout manager in Site and Page;
Added two more types: LayoutConfig and PageNjkAssets to avoid any
Fix some nits/bugs? along the way: 
in Site: 
  await this.layoutManager.updateLayouts(filePath) 
  => 
  await this.layoutManager.updateLayouts(filePathArray)

and in Layout.ts

  generateDependencies(pageSources.getDynamicIncludeSrc(),
                                           this.includedFiles)
  => 
  await this.config.externalManager.generateDependencies(
      pageSources.getDynamicIncludeSrc(),
      this.includedFiles,
      this.layoutUserScriptsAndStyles);
  }
  

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Migrate layout to Typescript
---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Comment by yucheng11122017** [comment]
Hi @yiwen101 sorry I won't have time to check this tonight but migrating TS PRs should only have 2 commits as per [DG](https://markbind.org/devdocs/devGuide/development/migratingToTypeScript.html#optional-step-4-changing-the-commit)
Could you follow the instructions there? Thanks!

**Comment by yiwen101** [comment]
> Hi @yiwen101 sorry I won't have time to check this tonight but migrating TS PRs should only have 2 commits as per [DG](https://markbind.org/devdocs/devGuide/development/migratingToTypeScript.html#optional-step-4-changing-the-commit)
> Could you follow the instructions there? Thanks!

Haha, sure; will open a new PR;

Actually unsure of whether I could press "update this branch"  or need to ` amend, force push`, I clarify by sharing my screen during today's meeting and get responded that I could simply press "update this branch" :(

**Comment by kaixin-hc** [comment]
My bad @yiwen101 ! While generally you can press update this branch, you need to take particular care for typescript migration due to our established workflow, and I didn't realize the context when I gave that advice

(I think if you had clicked update this branch with rebase it would have been okay)

 Normally, it doesn't matter because PRs are squash-merged, but in this case it does since we're trying to preserve the doc history.

**Comment by yiwen101** [comment]
> My bad @yiwen101 ! While generally you can press update this branch, you need to take particular care for typescript migration due to our established workflow, and I didn't realize the context when I gave that advice
> 
> (I think if you had clicked update this branch with rebase it would have been okay)
> 
> Normally, it doesn't matter because PRs are squash-merged, but in this case it does since we're trying to preserve the doc history.

Noted, thank you for the detailed explaination!

**Pull request closed without merging**
