### PR TITLE
Fix bug to allow highlighting of code with '-'

### PR DESCRIPTION
**Pull request by yucheng11122017**
**Note:** this PR is a follow-up to #2125 to rectify the accidental merge.

**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Trying to highlight code which contained a '-' did not work since the highlight rules were parsed according to '-'.
Eg. {highlight-lines="1['block-level']"}
Change to parse using regex in which '-' cannot be within a ```[]```.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**
````
 ```{highlight-lines="1['block-level']"}
<markdown> elements allow block-level markdown without needing a leading newline.
Hence, the contained markdown should be parsed and output as is, without any parsing errors.
</invalidhtml>
 ```
````

**Proposed commit message: (wrap lines at 72 characters)**
```Fix bug to allow highlighting of code with '-'```

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [X] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes

### CODE REVIEW

**Review by ong6 — APPROVED** [review]
LGTM

**Review by jovyntls — CHANGES_REQUESTED** [review]
Thanks for adding test cases!
Found an edge case starting with dash: 
{highlight-lines="1['-block-level']"}
<markdown> elements allow -block-level markdown without needing a leading newline.
Hence, the contained markdown should be parsed and output as is, without any parsing errors.
</invalidhtml>

**Review by jovyntls — APPROVED** [review]
Working on my end! LGTM

**Comment by tlylt** [comment]
@all-contributors please add @yucheng11122017 for code

**Pull request merged**
