### PR TITLE
Update MarkBind website URL

### PR DESCRIPTION
**Pull request by yamgent**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Other, please explain: Update README.md

**What is the rationale for this request?**

We migrated from https://markbind.github.io/markbind/ to https://markbind.org/

### CODE REVIEW

**Comment by damithc** [comment]
We can jump ahead and change it to marbind.org too

**Comment by yamgent** [comment]
Ok, I have added a CNAME for it as well to the original website. 

@damithc need you to disable the redirection for the `https://markbind.org` domain.

**Comment by damithc** [comment]
I've updated on the GoDaddy side just now. Will take some time for it to start working I guess.

**Comment by damithc** [comment]
Working now :-)

**Pull request merged**
