### PR TITLE
Update search during live preview

### LINKED ISSUE #541: Make search compatible with live preview
v1.15.2

Current: the search index of the live preview does not update to reflect changes to headings of a page, although it reflects changes to keywords specified in the `<frontmatter>` of a page.
Steps:
1. launch live preview of a site that has a search bar
2. add a heading to a page
3. search for that heading in the live preview
4. actual: the heading does not show in results unless the live preview is restarted

Note: even `--force-reload` flag seem to make the search index live-update.

Suggestions:
* Make search compatible with live preview
* Failing the above, make it compatible with the `--force-reload` flag
* Failing the above, document this limitation in the user docs

### PR DESCRIPTION
**Pull request by nicholaschuayunzhi**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [ ] Documentation update
• [x] Bug fix
• [ ] New feature
• [ ] Enhancement to an existing feature
• [ ] Other, please explain:

**What is the rationale for this request?**
Fixes #541 

**What changes did you make? (Give an overview)**
During reload, collect heading data. Previously it was re-writing site data without re-collecting heading information.

Also refactored site data generation into one function and updated the build function to use.

**Is there anything you'd like reviewers to focus on?**
Refactoring of site data generation.

**Testing instructions:**
Create site with search and run live preview

1. Update header
1. Update front matter keywords
1. See update in search

### CODE REVIEW

**Comment by damithc** [comment]
@nicholaschuayunzhi is there an impact on performance (for big sites)?

**Comment by nicholaschuayunzhi** [comment]
Apologies for testing extensively. For 2103 website base, reloading the site data adds an additional 23s to the reload time.. I'll see what I can do to reduce the timing. Alternatively we can add another option to prevent the reload?

**Comment by damithc** [comment]
> I'll see what I can do to reduce the timing. Alternatively we can add another option to prevent the reload?

Yes, we can add a switch to control this feature.

**Comment by nicholaschuayunzhi** [comment]
I've updated the feature to only update site data of affected files during reload #568

**Comment by damithc** [comment]
> I've updated the feature to only update site data of affected files during reload #568

Nice. Thanks @nicholaschuayunzhi

**Pull request merged**
