### PR TITLE
Update copy plugin

### LINKED ISSUE #2579: Have code blocks show more UI details/ be more responsive
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### What is the area that this feature belongs to?

Plugins

### Is your feature request related to a problem? Please describe.

Although a minor inconvenience, a lack of response from the copy plugin buttons can cause some confusion on whether the action have been performed. 

### Describe the solution you'd like

A more responsive plugin button that changes its icons when clicked on. I have tried implementing it below,

image

The copy button would show a tick when it is clicked on. And change back to the copy button after some time.

### Describe alternatives you've considered

_No response_

### Additional context

If the suggestion is sound, I can submit my PR for this issue.

### PR DESCRIPTION
**Pull request by Incogdino**
Previously, copy plugin does not indicate a response when the code block is copied. A more informative response can help improve user experience when copying the code block.

**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [X] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
This PR closes #2579.

The copy button lacked response when copying from a code block. An added response such as a tick can improve the systems feedback to the user making it slightly more enjoyable to use.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**
nil

**Proposed commit message: (wrap lines at 72 characters)**
Update copy plugin

Previously, copy plugin does not indicate a response when the code
block is copied. A more informative response can help improve user
experience when copying the code block.

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [ ] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Comment by yucheng11122017** [comment]
Hi @Incogdino this is great work! Thanks for the contribution. Definitely an interesting and helpful UI change. 
Sorry for being particular but could you revert the white spaces changes you made that doesn't actually affect the code? This is just to make it easier for us to read. I'll review it once you are done! Do ping me after

Also another point to consider is if we should allow a user to disable this if they want.. but this can be discussed in another issue since the user SHOULD want this in the first place (and is very minor change to their UI)

**Comment by Incogdino** [comment]
> Hi @Incogdino this is great work! Thanks for the contribution. Definitely an interesting and helpful UI change. Sorry for being particular but could you revert the white spaces changes you made that doesn't actually affect the code? This is just to make it easier for us to read. I'll review it once you are done! Do ping me after
> 
> Also another point to consider is if we should allow a user to disable this if they want.. but this can be discussed in another issue since the user SHOULD want this in the first place (and is very minor change to their UI)

@yucheng11122017 thanks for the review. I have changed the indent back to 4 spaces and alphabetize the attributes I added. I'm a bit unsure about the indentations for the css file since the [css coding standard](https://se-education.org/guides/conventions/css.html) stated on the dev guide suggested an indentation of 2 spaces.

Allowing users to choose whether they want to enable this feature is a great point too!

**Review by yucheng11122017 — APPROVED** [review]
Hi @Incogdino Thanks for the great work! LGTM :) We can discuss disabling this in another issue. Was also thinking about adding a notification (which I think is quite common) saying copied!

This is from leetcode which I think is quite nice: 
https://github.com/user-attachments/assets/c6e4ede6-4dec-44ad-8cc7-e605bbb4b2b7

**Comment by yucheng11122017** [comment]
@all-contributors please add @Incogdino for code

**Pull request merged**
