### PR TITLE
Add UG for GitHub Action

### PR DESCRIPTION
**Pull request by le0tan**
**What is the purpose of this pull request?**

- [X] Documentation update

Related to #1004 

**Proposed commit message: (wrap lines at 72 characters)**

Add instruction link to markbind-action

**Checklist:** :ballot_box_with_check:

### CODE REVIEW

**Comment by ang-zeyu** [comment]
@le0tan are there any other planned changes? (seeing that its a draft)

I'll merge this in otherwise : - )

**Comment by damithc** [comment]
Tried in https://nus-cs3281.github.io/2021 and worked 👍

**Comment by ang-zeyu** [comment]
I've marked the action as prerelease for now.

Realised this minimally needs a markbind version option in case of breaking changes, and preferably a force push option highlighted in #1461.

This will be covered by #1460 for v3.0 as well, but we can still publish this for use in v2.7.x.
A better time to publish it might be once this has support for #1009 though. (otherwise it would be covered by #1460 as well)

**Comment by le0tan** [comment]
@ang-zeyu what's the plan for this action to support #1009 ?

**Pull request closed without merging**
