### PR TITLE
Make pop-ups accessible

### LINKED ISSUE #1745: Popover components are not accessible
**Tell us about your environment**
MacOS Monterey 12.0.1

* **MarkBind Version:**
v3.1.1

**What did you do? Please include the actual source code causing the issue.**
Create a popover component without a trigger component, 
e.g. `<popover content="Lorem ipsum dolor sit amet" triggers="focus">Popover on top</popover>`

**What did you expect to happen?**
For accessibility purposes, the popover should be open-able from the keyboard to cater to keyboard-only users.

**What actually happened? Please include the actual, raw output.**
The popover content (in the above example, "Popover on top") is not focus-able by keyboard even when the `triggers` attribute is set to `focus`.
Furthermore, when a trigger method is not specified, currently MarkBind defaults to `hover`. However, this poses accessibility issues as `hover` is [impossible to trigger for keyboard-only users](https://bootstrap-vue.org/docs/directives/popover#making-popovers-work-for-keyboard-and-assistive-technology-users). 

Suggestion: Maybe we could set the default value of `triggers` to `"hover focus"`? This would maintain the expected hover behaviour, and also allow for accessibility for keyboard-only users. I think such a change would not be noticeable for most users, but would be helpful in terms of accessibility.

### PR DESCRIPTION
**Pull request by jovyntls**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

Fixes #1745 

**Overview of changes:**
Change the default trigger from `hover` to `hover focus` 
- bootstrap-vue documentation mentions that [`hover` is impossible to trigger for keyboard users](https://bootstrap-vue.org/docs/components/popover#making-popovers-work-for-keyboard-and-assistive-technology-users)

**Anything you'd like to highlight / discuss:**
N/A

**Testing instructions:**
Using the tab key to navigate the page should cause pop-ups to be displayed when they are in focus (i.e., when they are tabbed over)

**Proposed commit message: (wrap lines at 72 characters)**
```
Improve accessibility of pop-ups

According to the bootstrap-vue docs, the default value of `hover` for
popups is impossible to trigger for keyboard users, resulting in
accessibility issues.

Let's use `hover focus` as the default value, as this provides an
additional and unobtrusive way of displaying pop-up contents.
```

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Review by tlylt — COMMENTED** [review]
> Using the tab key to navigate the page should cause pop-ups to be displayed when they are in focus (i.e., when they are tabbed over)

Tested on the preview [here](https://deploy-preview-1833--markbind-master.netlify.app/userguide/components/popups#popovers) and worked 👍

For this part:
> Name | Type | Default | Description
---- | ---- | ------- | ------
trigger | `String` | `hover focus` | How the overlay view is triggered.<br>Supports: `click`, `focus`, `hover`.

We say in the description that it supports 'click', 'focus', 'hover', but the value we use is 'hover focus', which is not part of the above. Seems a bit confusing?

**Comment by jovyntls** [comment]
@tlylt That's true, thanks for the catch! I've changed it to:

> Supports: `click`, `focus`, `hover`, or any space-separated combination of these.

**Review by jonahtanjz — APPROVED** [review]
Thanks @jovyntls 

LGTM 👍

**Comment by kaixin-hc** [comment]
It looks good! I'm wondering if these accessibility improvements can also be applied to modals. [On this page](https://deploy-preview-1833--markbind-master.netlify.app/userguide/components/popups#modals), I can't seem to activate the modals by focusing on them with the keyboard.

**Comment by jovyntls** [comment]
> It looks good! I'm wondering if these accessibility improvements can also be applied to modals. [On this page](https://deploy-preview-1833--markbind-master.netlify.app/userguide/components/popups#modals), I can't seem to activate the modals by focusing on them with the keyboard.

It looks like the case for modals might be a bit tricky. When a modal is opened through `focus`, the focus moves away from the trigger. When the modal is closed, the focus automatically returns to the trigger, which makes makes the modal open again, which results in being unable to ever close the modal once it has been opened using `focus`, a bit like an infinite loop. (Popovers and tooltips don't have this problem because the focus remains on the popover/tooltip even after it is activated.)

One way to circumvent this could be to [manually return the focus](https://bootstrap-vue.org/docs/components/modal) by adding a non-visible dummy element after the trigger for modals? I'm not sure if this will have any implications though

**Pull request merged**
