### PR TITLE
Add animation when closing panel with bottom switch

### LINKED ISSUE #2337: Closing a panel without animation is disorientating
In https://github.com/MarkBind/markbind/pull/2159 we removed the closing animation for panels. 
But now, closing a panel results in a sudden change of content in the page and it is very hard to find where one was before. We need to bring back that animation, at least for shorter panels.

### PR DESCRIPTION
**Pull request by yucheng11122017**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [X] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Resolves #2337

**Overview of changes:**
Add animation when user clicks on switch at the bottom of the panel if the top of the panel is out of the page

**Anything you'd like to highlight/discuss:**
nil

**Testing instructions:**
Create a panel and open it 
Scroll down until the top of the panel is out of the page 
Click on the bottom switch
See there is animation as the page scrolls to the top of the panel

**Proposed commit message: (wrap lines at 72 characters)**
Add animation when closing panel with bottom switch

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes

### CODE REVIEW

**Comment by tlylt** [comment]
@yucheng11122017 possible to record a before and after video? I'm not sure what has changed.

**Comment by damithc** [comment]
> After: https://github.com/MarkBind/markbind/assets/77204346/0a8f4167-cc47-4631-aaf1-c69d00d3e333

Looks good @yucheng11122017

**Review by tlylt — APPROVED** [review]

**Review by tlylt — CHANGES_REQUESTED** [review]
@yucheng11122017 can we make it the default for all panels? i.e. minimal panel should also have this behavior.

**Comment by yucheng11122017** [comment]
Sorry for the late response @tlylt it should work now!

**Review by tlylt — APPROVED** [review]

**Pull request merged**
