### PR TITLE
Revert migration to dayjs

### PR DESCRIPTION
**Pull request by tlylt**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [x] Others, please explain: Revert PR to prevent unexpected version update

**Overview of changes:**
See discussions at https://github.com/MarkBind/markbind/pull/2007/files#r950776502
- Reverting because dayjs does not fully cover all formats of Momentjs, hence breaking backward compatibility unannounced 

**Anything you'd like to highlight/discuss:**
When adding moment back in via `npx lerna add moment packages/core`, I am faced with the following error:
image

Full log:

> 0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.24.2
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\User\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 6ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:C:\Users\User\Documents\GitHub\markbind\packages\cli\.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\Users\User\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\User\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 3ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 22ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 1ms
29 timing idealTree:init Completed in 39ms
30 warn old lockfile The package-lock.json file was created with an old version of npm,
30 warn old lockfile so supplemental metadata must be fetched from the registry.
30 warn old lockfile
30 warn old lockfile This is a one-time fix-up, please be patient...
31 silly inflate node_modules/@markbind/core-web
32 silly inflate ../core-web
33 silly inflate ../core-web/node_modules/@markbind/vue-components
34 silly inflate ../vue-components
35 silly inflate node_modules/@markbind/core
36 silly inflate ../core
37 silly inflate ../core/node_modules/@markbind/core-web
38 timing idealTree Completed in 52ms
39 timing command:install Completed in 60ms
40 verbose stack Error: Tracker "idealTree:inflate:" already exists
40 verbose stack     at Arborist.[_onError] (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\tracker.js:107:11)
40 verbose stack     at Arborist.addTracker (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\tracker.js:31:21)
40 verbose stack     at Array.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:717:14)
40 verbose stack     at run (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\promise-call-limit\index.js:30:26)
40 verbose stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\promise-call-limit\index.js:39:5
40 verbose stack     at new Promise (<anonymous>)
40 verbose stack     at callLimit (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\promise-call-limit\index.js:2:48)
40 verbose stack     at Arborist.[inflateAncientLockfile] (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:732:11)
40 verbose stack     at Arborist.buildIdealTree (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:209:42)
40 verbose stack     at async Promise.all (index 1)
41 verbose cwd C:\Users\User\Documents\GitHub\markbind\packages\cli
42 verbose Windows_NT 10.0.19043
43 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
44 verbose node v14.17.0
45 verbose npm  v7.24.2
46 error Tracker "idealTree:inflate:" already exists
47 verbose exit 1

Wonder @ang-zeyu if you know why this is the case? I think it has been like this for a long time, which is why in the previous PR I manually added the dependency in package.json first.

For the above, after seeing the error, the "moment" dependency is still updated correctly in package.json, so I rerun `npm run setup` to fix the lock and everything seems ok ... just curious if this is something that we can resolve.

**Testing instructions:**
nil

**Proposed commit message: (wrap lines at 72 characters)**
Revert migration to dayjs

Previous migration to dayjs did not take into account of the full
list of date time formats that are supported by momentjs. Hence
the migration could potentially break the user's website.

Let's revert the migration and bump the momentjs version to latest.

Since momentjs is still in maintenance, we can put off the migration
until proper planning and discussions have been conducted.

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

**Comment by ang-zeyu** [comment]
> For the above, after seeing the error, the "moment" dependency is still updated correctly in package.json, so I rerun npm run setup to fix the lock and everything seems ok ... just curious if this is something that we can resolve.

I'm not getting this error, but I'm on npm 8.5.5 currently.

Does upgrading your npm version work? It might be that our current package-lock is created with npm >= 8, hence the issue.

This is actually my first time using `npx lerna add` as well, I wrongly assumed it would work out of the box (seems like it chains a [bootstrap](https://github.com/lerna/lerna/tree/main/commands/add#readme) call without the `--hoist` option). I think the right procedure should be to either:

- ` npx lerna add moment packages/core --no-bootstrap` + `npm run setup`
- manually add the dependency into the package.json + `npm run setup` (what I've been doing)

**Review by ang-zeyu — APPROVED** [review]
> I think the right procedure should be to either:

If that sounds right I'll push a quick update shortly. I think it'd be best to avoid `lerna add` completely.


The change lgtm otherwise, don't see any changes from `npm run setup` either. 🙂

**Comment by tlylt** [comment]
> I'm not getting this error, but I'm on npm 8.5.5 currently.
> 
> Does upgrading your npm version work? It might be that our current package-lock is created with npm >= 8, hence the issue.

I see, I am not too sure because some lerna add requests for my git passphrase and I am now stuck because it doesn't authenticate me...

> This is actually my first time using npx lerna add as well, I wrongly assumed it would work out of the box (seems like it chains a [bootstrap](https://github.com/lerna/lerna/tree/main/commands/add?rgh-link-date=2022-09-03T05%3A14%3A21Z#readme) call without the --hoist option). I think the right procedure should be to either:

npx lerna add moment packages/core --no-bootstrap + npm run setup
manually add the dependency into the package.json + npm run setup (what I've been doing)

> If that sounds right I'll push a quick update shortly. I think it'd be best to avoid lerna add completely.

Not too sure about the lerna bootstrap part, but the manually add and run setup works for me so far.

**Comment by ang-zeyu** [comment]
> I see, I am not too sure because somehow lerna add requests for my git passphrase and I am now stuck because it doesn't authenticate me...

It might be an excessive check over at lerna (I think some operations do require that), and/or we are using an older version of lerna.

But I don't think I've had this occur to me before, it likely uses the same global git credential stores. Would try checking if other areas / git operations are working fine in your environment.

**Pull request merged**
