### PR TITLE
Update Node version to 20

### LINKED ISSUE #2496: Document: Node LTS (v20) and python 3.12 does not work on MarkBind install
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

M2 Mac v13.6.6

### MarkBind version

5.4.0

### Describe the bug and the steps to reproduce it

When running `npm install` in the root of markbind, see the following error:
node-gyp error

This error is caused because 3.12 python deprecates distutils, and node-gyp packaged with LTS is a node-gyp version before version 10. As stated in [this issue](https://github.com/nodejs/node-gyp/issues/2942), python 3.12 needs the newer version of node-gyp. It seems non trivial to update node-gyp version, as the [official instructions here did not work for me](https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md) (needs more testing).

However, one workaround that worked for me was adding the following line to node config 
`python=path/to/python/on/my/device` and downgrading my python version (`brew uninstall python@3.12` - though i had to force uninstall it due to dependencies)

(I also had to delete and reclone my MarkBind, but I suspect that was unrelated)

### Expected behavior

If the versions are not supported, we should maybe warn users of the problem since right now we just say the following about required version...
Screenshot 2024-04-04 at 4 34 54 PM

### Anything else?

Thank you @lhw-1 and @EltonGohJH for your extensive help troubleshooting this issue!

### LINKED ISSUE #2541: Update Node version to LTS
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2197

### What is the area that this feature belongs to?

_No response_

### Is your feature request related to a problem? Please describe.

Upgrade to Node to LTS either 18 or 20.
(Node 16 EOL was 09 Aug 2023)

### Describe the solution you'd like

Similar to what we have done previously. You can refer to #2197

Before the version update, check that
- [ ] all user-facing functionalities are working
- [ ] no issues with the development setup
- [ ] whether related GitHub Actions need to be updated
- [ ] any deprecated syntax to be refactored
- [ ] docs are updated
- [ ] Deployment to Netlify/other platforms is ok

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gerteck**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
This PR seeks to upgrade Node.js to Node 20. 
* Relevant MB documentation on Node.js [migration](https://markbind.org/devdocs/devGuide/development/migratingNodeJs.html)
* Previous upgrading Node 14 -> 16 [PR](https://github.com/MarkBind/markbind/pull/2233)

Addresses and Fixes #2541 

**Anything you'd like to highlight/discuss:**

Before the version update, check that

* [x] any deprecated syntax to be refactored
* [x] all user-facing functionalities are working
* [x] no issues with the development setup
  * Tested on fresh Ubuntu VM, node v20.16.0
* [x] update related GitHub Actions and workflows
  * [x] Test updated Actions 
* [x] docs are updated
* [x] Deployment to Netlify/other platforms is ok
  * [x] Netlify (PRs [1](https://github.com/MarkBind/init-typical-netlify/pull/5), [2](https://github.com/MarkBind/init-minimal-netlify/pull/5) opened for netlify quickstart repos to update node version number)
  * [x]  GH-Pages
* [ ] Deployment via CI platforms is ok 
  * [x] GH Actions [test run](https://github.com/gerteck/mb-test-deploy/actions/runs/10441899051/job/28913584558)
  * (Other platforms can't be tested due to deployment cachedir bug, need new release to update previous patch by #2562 )
  * [ ] Travis CI (education plan also suddenly expired)
  * [ ] AppVeyor CI
  * [ ] Circle CI
* [x] Update `netlify.toml`

**Related PRs:**
* https://github.com/MarkBind/markbind-action/pull/16
* https://github.com/MarkBind/init-typical-netlify/pull/5
* https://github.com/MarkBind/init-minimal-netlify/pull/5

**Related Changes**
* https://github.com/MarkBind/markbind/pull/2565 
  * (Resolves #2496)
* https://github.com/MarkBind/markbind/pull/2536 (Changes Reverted)

**Other:**
Node.js Changelogs
* [Node v17.0](https://nodejs.org/en/blog/release/v17.0.0)
* [Node v18.0](https://nodejs.org/en/blog/release/v18.0.0)
* [Node v19.0](https://nodejs.org/en/blog/release/v19.0.0)
* [Node v20.0](https://nodejs.org/en/blog/release/v20.0.0)

**To-do:**
* [x] Test deployment via other CI platforms once MarkBind ver is updated to reflect latest patches.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

Upgrade Node.js to v20

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [ ] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Comment by Tim-Siu** [comment]
Hi @gerteck,

Thank you for your meticulous work on this PR!

I noticed the note about testing deployment via other CI platforms once the MarkBind version is updated to reflect the latest patches. Could you perhaps elaborate on why this testing is contingent on the MarkBind version update? I'm curious to understand what these patches entail and how they relate to the deployment testing.

**Comment by gerteck** [comment]
>  Could you perhaps elaborate on why this testing is contingent on the MarkBind version update? I'm curious to understand what these patches entail and how they relate to the deployment testing.

Sure!

I was referencing the patch in PR #2562 , which in short fixes `markbind deploy` without the explicit need to set the cache_dir as per #2547. Previously, `markbind deploy` would fail on deployment outside of GitHub Actions. This patch is necessary for testing in the ci/cd workflow, since we essentially do:

```
npm i -g markbind-cli
markbind build
markbind deploy --ci
```
ciexample

That said, I suppose a hacky workaround would be to explicitly set env variables (specifically `cache_dir`) etc in the CI platforms to get around this issue, ceteris paribus, to test the deployment before the patch is made. Though it would be quite out of context.

This issue probably wasn't detected because #2542 had patched this issue in `markbind deploy`, but only specifically in GitHub Action's environment, with no testing done for Travis CI, AppVeyor or other CI platforms.

---

The other patches aren't required for deployment testing, even #2565 (which was a considerable issue when migrating to node 20, but doesn't affect deployment since it's a dev-dependency). Also, this issue was actually also why I focused working on #2562 earlier on prior.😄

**Comment by Tim-Siu** [comment]
Hey @gerteck,

Thanks for explaining everything and for all the testing you've done. It's clear you've put in a lot of work, especially with the workaround for the cache_dir issue. I think it's a good idea to update the MarkBind version as it would certainly save efforts, and I'll check with our seniors for their thoughts.

@yucheng11122017, could you take a look at this when you have a moment? With what @gerteck has shared, it seems like updating the MarkBind version (doing a new release) that includes the fixes from PR #2562, could help with our deployment testing on different CI platforms. What do you think about doing the update?

**Comment by tlylt** [comment]
Thanks @gerteck for your work on this PR!

As outlined in our [docs](https://markbind.org/devdocs/devGuide/development/settingUp.html), we aim to support up to the last maintenance lts, which at the moment should be Node v18 (currently on maintenance support). Jumping directly to Node v20 is probably not what we want, unless you have some reasons for this? (Sorry the issue linked was probably not accurate)

We do need to update to v18 ASAP though. If you are keen, I would suggest we close this PR and open a new one to make the changes for v18 migration.

As for your CI testing comment, I can make a release over the weekend for the few fixes you have made (TQ again).

**Comment by gerteck** [comment]
> As outlined in our [docs](https://markbind.org/devdocs/devGuide/development/settingUp.html), we aim to support up to the last maintenance lts, which at the moment should be Node v18 (currently on maintenance support). Jumping directly to Node v20 is probably not what we want, unless you have some reasons for this? (Sorry the issue linked was probably not accurate)

The main reason why I directly jumped to Node v20 was because GitHub actions is transitioning directly from [node 16 to 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Although it seems that it has not been actively enforced yet.

> We do need to update to v18 ASAP though. If you are keen, I would suggest we close this PR and open a new one to make the changes for v18 migration.

Sure, that would be possible!

**Comment by gerteck** [comment]
Just for reference, here is the deployment via CI before and after making the new release:

Travis CI:
* [before](https://app.travis-ci.com/github/gerteck/mb-test-deploy/builds/271202182#L261): see error under deploying application
* [after](https://app.travis-ci.com/github/gerteck/mb-test-deploy/builds/272278379#L246): see success under deploying application

AppVeyor CI:
* [before](https://ci.appveyor.com/project/gerteck/mb-test-deploy-2/builds/50119676)
* [after](https://ci.appveyor.com/project/gerteck/mb-test-deploy-2/builds/50583264)

Circle CI:
* [after](https://app.circleci.com/pipelines/github/gerteck/mb-test-deploy-2/2/workflows/ae624909-4699-487a-8ab1-9c79493108b8/jobs/2)

Thanks again @tlylt for making the new release.

**Comment by gerteck** [comment]
Will close this PR in favor of more updated #2572

**Pull request closed without merging**
