### PR TITLE
Fix bug in search for dev guide

### LINKED ISSUE #1107: Search shows duplicate for Developer Guide
**Tell us about your environment**
MacOS

* **MarkBind Version:**
Latest master (for developers)

**What did you do? Please include the actual source code causing the issue.**

N.A.

**What did you expect to happen?**
Expected it to appear only once. 

**What actually happened? Please include the actual, raw output.**
Screen Shot 2020-03-09 at 3 35 38 PM

### PR DESCRIPTION
**Pull request by Tejas2805**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Bug fix

Fixes #1107 

**What is the rationale for this request?**
It becomes confusing to see the same results twice. 

**What changes did you make? (Give an overview)**

Changed the navigation layout for developer guide and maintainer guide

**Provide some example code that this change will affect:**

```html
<navigation>

<span class="lead">**Developer Guide**</span>

* [Maintainer Guide]({{baseUrl}}/devGuide/maintainerGuide.html)
</navigation>
```

**Is there anything you'd like reviewers to focus on?**
N.A.

**Testing instructions:**
Can check deployed

**Proposed commit message: (wrap lines at 72 characters)**

### CODE REVIEW

**Comment by ang-zeyu** [comment]
Hmm the duplicate results still occurs, as `index.md` includes `devGuide.md` as a static include.

A simple fix for this would be to simply rename `devGuide.md` to `index.md`.

**Comment by damithc** [comment]
> Hmm the duplicate results still occurs, as `index.md` includes `devGuide.md` as a static include.
> 
> A simple fix for this would be to simply rename `devGuide.md` to `index.md`.

How about some kind of redirection mechanism? In CS2103, landing page content changes over time (e.g., before the semester starts vs during the semester). Currently, I use a static include to change the content easily.

**Comment by Tejas2805** [comment]
> A simple fix for this would be to simply rename `devGuide.md` to `index.md`.

Ah I see. Just noticed this when you said it. 

1) Remove the `index.md` file and refer it to `devGuide.md` 
2) If we wanna keep `index.md`, we just rename `devGuide.md` to `index.md`

**Comment by ang-zeyu** [comment]
> How about some kind of redirection mechanism? In CS2103, landing page content changes over time (e.g., before the semester starts vs during the semester). Currently, I use a static include to change the content easily.

> 1. Remove the `index.md` file and refer it to `devGuide.md`
> 2. If we wanna keep `index.md`, we just rename `devGuide.md` to `index.md`

Redirection sounds good; We might want to include a "landing page" for the developer guide different from `devGuide.md` somewhere in the future.

**Comment by Tejas2805** [comment]
Not exactly sure what you mean by redirection. Can you guide a bit?

**Comment by ang-zeyu** [comment]
> Not exactly sure what you mean by redirection. Can you guide a bit?

Something like `window.location.href = "..."` should work!

**Comment by ang-zeyu** [comment]
@Tejas2805 should we close this?

**Comment by Tejas2805** [comment]
Have closed this

**Pull request closed without merging**
