### PR TITLE
Fix missing return termination

### PR DESCRIPTION
**Pull request by jonahtanjz**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

**Overview of changes:**
Follow up to PR #1446

Missed out on a [return termination](https://github.com/MarkBind/markbind/pull/1446#discussion_r607076078) in the `rebuildRequiredPages` method.

**Anything you'd like to highlight / discuss:**
`NIL`

**Testing instructions:**
`NIL`

**Proposed commit message: (wrap lines at 72 characters)**
Fix missing return termination in rebuildRequiredPages

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No blatantly unrelated changes
- [x] Pinged someone for a review!

### CODE REVIEW

**Comment by wxwxwxwx9** [comment]
@jonahtanjz LGTM! But just to clarify why this fix is required. 

In this async function, if we don't have the return statement, then what is implicitly returned is a promise that resolves to undefined. If we add this `return`, would it also implicitly return a promise that resolves to undefined?

**Comment by jonahtanjz** [comment]
@wxwxwxwx9 Thanks for the review!

>But just to clarify why this fix is required.

The return termination is required so that if `this.onePagePath` is true, it should lazy build all the other pages and should not run `this.buildSourceFiles()`. Therefore it should terminate after `this.lazyBuildAllPagesNotViewed()`.

>In this async function, if we don't have the return statement, then what is implicitly returned is a promise that resolves to undefined. If we add this return, would it also implicitly return a promise that resolves to undefined?

IIRC an async function will return a promise that will resolve to the return value of that function. In this case, `return;` will return `undefined` and hence the async function should also return a promise that resolves to `undefined`.

**Comment by wxwxwxwx9** [comment]
> The return termination is required so that if this.onePagePath is true, it should lazy build all the other pages and should not run this.buildSourceFiles(). Therefore it should terminate after this.lazyBuildAllPagesNotViewed().

Ah right, missed this part. Initially I was thinking the fix had something to do with promise resolution. Thanks for clarifying!

**Review by wxwxwxwx9 — APPROVED** [review]
LGTM!

**Pull request merged**
