### PR TITLE
Configure docs to use light style

### LINKED ISSUE #1376: Use light style for code blocks in our own documentation
Our documentation was written when we only had the light style for fenced code blocks, and hence, the documentation doesn't look nice in the dark style (too many dark boxes within a page because we use a lot of in-line code).
Shall we set it to the light style?

I'm also wondering if we should allow controlling the inline style independently from the non-inline code blocks? Would people want to use light style for inline but dark style for non-inline?

### PR DESCRIPTION
**Pull request by ryoarmanda**
**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

Resolves #1376

**Overview of changes:**
- Use `codeTheme: "light"` on documentation `site.json`s

**Anything you'd like to highlight / discuss:**

**Testing instructions:**
I suppose to directly check the Netlify site.

**Proposed commit message: (wrap lines at 72 characters)**
Configure docs to use light style for code blocks

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No blatantly unrelated changes
- [x] Pinged someone for a review!

### CODE REVIEW

**Comment by ryoarmanda** [comment]
@ang-zeyu can help me review this? It's a very short one :)

@damithc can also verify with the Netlify deploy site first.

**Comment by damithc** [comment]
The preview looks good. BTW, shouldn't we mention the dark theme somewhere in https://deploy-preview-1380--markbind-master.netlify.app/userguide/formattingcontents#code ?

**Comment by ryoarmanda** [comment]
I have mentioned the dark theme at https://deploy-preview-1380--markbind-master.netlify.app/userguide/sitejsonfile#style before  as an explanation to the `codeTheme` property. I can add a brief aside to the "Formatting Contents" section that dark theme exists and direct authors to the "`site.json` File" section to enable it.

**Comment by damithc** [comment]
> I have mentioned the dark theme at https://deploy-preview-1380--markbind-master.netlify.app/userguide/sitejsonfile#style before as an explanation to the `codeTheme` property. I can add a brief aside to the "Formatting Contents" section that dark theme exists and direct authors to the "`site.json` File" section to enable it.

Yes, only a brief mention of it's existence is needed.

**Comment by ang-zeyu** [comment]
will `dg-site.json` still be using the dark theme? 😮

**Comment by ryoarmanda** [comment]
> will dg-site.json still be using the dark theme?

Oh, looks like I missed that. But weirdly, the dg in Netlify already uses light style. Probably due to the configuration in `site.json`. But in any case, I will add the light theme to `dg-site.json` too

**Review by ang-zeyu — APPROVED** [review]
> Oh, looks like I missed that. But weirdly, the dg in Netlify already uses light style. Probably due to the configuration in site.json. But in any case, I will add the light theme to dg-site.json too

yup, the netlify preview in prs uses `site.json`.

`dg-site.json` affects the deployed dev guide via travis (on every commit to the main branch)

**Pull request merged**
