### PR TITLE
docs: Add missing layout and css map files

### LINKED ISSUE #579: Layouts folder missing in docs causing error
Follow up from slack:

> I'm getting this on the [MarkBind website](https://markbind.github.io/markbind/):
> ```[Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/layouts/default/styles.css
> [Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/layouts/default/scripts.js
> [Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/css/bootstrap.min.css.map```
> The first two errors seem related to [Add page layouts functionality #439](https://github.com/MarkBind/markbind/pull/439).
> The third error is unrelated but I recall seeing it before; MarkBind should include the `.map` file.

This is because the docs site is missing the `layouts` folder that is usually added on `markbind init`.

### PR DESCRIPTION
**Pull request by jamos-tay**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug fix

Fixes #579 

**What is the rationale for this request?**

Follow up from slack:

> I'm getting this on the [MarkBind website](https://markbind.github.io/markbind/):
> ```[Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/layouts/default/styles.css
> [Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/layouts/default/scripts.js
> [Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/css/bootstrap.min.css.map```
> The first two errors seem related to [Add page layouts functionality #439](https://github.com/MarkBind/markbind/pull/439).
> The third error is unrelated but I recall seeing it before; MarkBind should include the `.map` file.

**What changes did you make? (Give an overview)**

This is because the docs site is missing the `layouts` folder that is usually added on `markbind init`, run `markbind init` on the folder to add the missing files.

### CODE REVIEW

**Comment by damithc** [comment]
In this specific case, MarkBind should not break if the default layout is missing. Instead, it should interpret it as _no default provided_. What do you guys think?

**Comment by acjh** [comment]
Please add "Fixes #579" to the PR description.

**Comment by jamos-tay** [comment]
Updated

**Comment by jamos-tay** [comment]
My bad, forgot to commit the map in test site

**Comment by jamos-tay** [comment]
Updated

**Pull request merged**
