### PR TITLE
Migrate template to TypeScript

### PR DESCRIPTION
**Pull request by lhw-1**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [X] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Part of #1913.

Migrates `packages/core/template/template.js` to TypeScript following the workflow specified [here](https://markbind.org/devdocs/devGuide/development/migratingToTypeScript.html).

This PR also builds on the changes made in PR #2148.

**Overview of changes:**

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Review by jovyntls — APPROVED** [review]
LGTM! TS migration is going well 🎊

**Review by raysonkoh — APPROVED** [review]
LGTM

**Comment by tlylt** [comment]
I think `validateTemplateFromPath() {` and `generateSiteWithTemplate() {` are suitable to be marked as private, making use of TypeScript to enforce access control. Should be ok for now since other migration PRs don't seem to deal with this aspect as well (or perhaps I overlooked it).

**Comment by raysonkoh** [comment]
Yea I think I general there needs to be some cleanup after the migration (which will hopefully be done soon) and marking suitable functions as private should be one aspect. The other migration PRs have not been focusing on this aspect.

**Pull request merged**
