### PR TITLE
Deploy changes to user guide on Netlify

### PR DESCRIPTION
**Pull request by nicholaschuayunzhi**
This pr introduces a netlify configuration which forces Netlify to install the `package.json` dependencies in `docs/` which contains the latest published version of `markbind-cli`, currently `v1.6.3`.

We cannot specify this dependency in `package.json` in the root directory as npm does not allow a dependency to be the same as the package name.

To set up Netlify:

https://deploy-preview-2--markbind-nic.netlify.com/userguide/netlifypreview

You can ignore the project setup (first 4 steps) and continue with the Netlify setup.

In step 5 , you can leave the build and publish directory to be blank.

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
> Users need to update package.json and package.lock.json every time they upgrade markbind?

If you are referring to markbind site repositories, the site owner has to do it and the version for markbind should reflect the version he wants the site to be built in so that Netlify can install the correct version of markbind in their environment and build.

On a related note:

Currently what we advise is to install markbind globally `$ npm install markbind-cli -g` which allows us to to use markbind as a command. 

I am thinking eventually, site owners should use a local version of markbind (specified by package.json) as some sites may depend on older version of markbind. This can be specified by doing `$ npm install markbind-cli --save`.

**Comment by nicholaschuayunzhi** [comment]
I have updated the [user guide](https://deploy-preview-2--markbind-nic.netlify.com/userguide/netlifypreview) to show a simple way to set up Netlify. The catch is that Netlify will always use the latest version of MarkBind when building. However, it does not require any `package.json` and `package.lock.json`. 

To use a specific version of MarkBind, we would still need to follow the old workflow which i have kept in the site.

**Comment by damithc** [comment]
Got it. 👍

**Comment by damithc** [comment]
Does this setup work for markbind/markbind? 
Note that the site is inside the /docs folder, not the root folder

I tried the setup and got this error
image

**Comment by damithc** [comment]
When showing how to fill up netlify settings, show the screenshot  of the empty form and give the values as regular text. That way, it is easy to update in future and people can copy paste the value from our doc to netlify.

**Comment by damithc** [comment]
On a separate but related note, I wonder if this will work for repos that has submodules, such as CS2103 website.

**Comment by damithc** [comment]
@nicholaschuayunzhi I invited you as an admin to the netlify for this site

**Comment by nicholaschuayunzhi** [comment]
I've deployed a fork of 2103 website on netlify. 
https://heuristic-jones-050f39.netlify.com/

Seems like the textbook is built https://heuristic-jones-050f39.netlify.com/book/index.html
But i have not fully checked it.

**Comment by nicholaschuayunzhi** [comment]
@damithc , seems like i have solution for our repository that lets us preview our documentation without this .toml file while still installing only the latest published version of `markbind-cli`

> When showing how to fill up netlify settings, show the screenshot of the empty form and give the values as regular text. That way, it is easy to update in future and people can copy paste the value from our doc to netlify.

**Pull request closed without merging**
