### PR TITLE
Fix modal positioning in panel headers

### PR DESCRIPTION
**Pull request by jovyntls**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

Fixes the positioning issues from #1909 

**Overview of changes:**
Fixes the styles from panel headers which was disrupting modal positioning.
- Change `margin: 0` to `margin-bottom: 0` which seems to be the minimal change that retains panel header styling without affecting modal positioning

**Anything you'd like to highlight / discuss:**
The CSS here was inherited from MarkBind/vue-strap, where it was first implemented for [minimal panels](https://github.com/MarkBind/vue-strap/pull/117)

**Testing instructions:**
Modals in panel headers should now be positioned correctly.

**Proposed commit message: (wrap lines at 72 characters)**
```
Fix modal positioning in panel headers
```

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Comment by karnatisrinivas** [comment]
https://deploy-preview-1910--markbind-master.netlify.app/userguide/syntaxcheatsheet

I assume the above is the deployment preview of commit @jovyntls made, That's some great work. But when I navigated to Page Navigation menus in syntax cheat sheet. I still get two modals that overlap with each other. 
Kindly review once.

**Comment by karnatisrinivas** [comment]
https://deploy-preview-1910--markbind-master.netlify.app/userguide/syntaxcheatsheet

I assume the above is the deployment preview of commit @jovyntls made, That's some great work. But when I navigated to Page Navigation menus in syntax cheat sheet. I still get two modals that overlap with each other. 
Kindly review once.

**Comment by jovyntls** [comment]
Hi @karnatisrinivas, thanks for looking through! However, this PR is not meant to fix the two overlapping modals. It's only meant to fix modals being positioned wrongly when they are used in a panel header, because the root cause of the overlapping modals is different.

**Comment by karnatisrinivas** [comment]
Oh my bad , i wasn't aware of that, I thought it meant to fix the issue. LGTM

**Review by tlylt — APPROVED** [review]
LGTM

**Review by ong6 — APPROVED** [review]
LGTM

**Pull request merged**
