### PR TITLE
Remove clear line

### LINKED ISSUE #384: Do not clear console when MarkBind is launched
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

When MarkBind is launched, the console is always cleared. This behavior is counter-intuitive for console users.

We can get rid of this behavior by removing line 28: https://github.com/MarkBind/markbind/blob/2f9461b4ea63ada3e4a2d6b2bdd062f996498e3d/index.js#L26-L30

### PR DESCRIPTION
**Pull request by jamos-tay**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug fix

Fixes #384 

**What is the rationale for this request?**
Prevent console clear when markbind is started.

**What changes did you make? (Give an overview)**
Remove `clear()` call and `require` reference.

**Testing instructions:**
* Run `markbind`
* Console does not clear

### CODE REVIEW

**Comment by jamos-tay** [comment]
Sure 👍

**Comment by acjh** [comment]
The **package-lock.json** file should be updated.

**Comment by jamos-tay** [comment]
My bad, updated

**Comment by yamgent** [comment]
Looks generally OK, however, I notice that your branch branched out from a very old version `1.7.2` (we are now at `1.12.0` :P).

old

1. Try to rebase on the latest `master` commit so that we can be confidently sure that the fix works.
1. Also might be a good time to squash the commits together into one.

**Pull request merged**
