### PR TITLE
Remove un-used renameSlot method

### LINKED ISSUE #2284: Remove unused renameSlot method
The [renameSlot](https://github.com/markbind/markbind/blob/63ed8520b1208ead38162628dd055bbd9f83d8c3/packages/core/src/html/vueSlotSyntaxProcessor.ts#L69-L85) method was previously used to log warnings for deprecated slots. 

This method is no longer used and can be fully removed, as we have completed all pending deprecations that may use this method.

### PR DESCRIPTION
**Pull request by bibhu107**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Fixes #2284 

**Overview of changes:**

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Remove un-used renameSlot method

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

**Comment by jovyntls** [comment]
Hi @bibhu107 , thank you for contributing to Markbind! 🥳 

We usually try to fix one issue per PR to avoid unrelated changes and keep a trackable history. Would you mind ensuring that this PR fixes only one issue? If you'd like to fix more than one, feel free to open second PR :)

Would be nice if you could fill in the template given in the issue description as well, especially the proposed commit message! (To check a checkbox, you can fill it in with an 'x', e.g. `[x]`)

**Comment by bibhu107** [comment]
Hello @jovyntls ,
Thanks for the suggestions! I have updated the PR description and made sure this PR has fix for only issue #2284 .

Thanks!

**Review by jovyntls — APPROVED** [review]
LGTM! Thanks again @bibhu107 🎉

**Comment by jovyntls** [comment]
@all-contributors please add @bibhu107  for code

**Pull request merged**
