### PR TITLE
Fix bug with quiz next button skipping questions

### LINKED ISSUE #2188: Quiz skipping questions when pressing next multiple times
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

No

### Tell us about your environment

MacOS Monterey

### MarkBind version

4.1.0

### Describe the bug and the steps to reproduce it

When pressing the next button multiple times (**before it disappears and goes to the next question**) and the next few questions are of multiple select or fill in the blanks type (which allow empty input as an answer), the quiz will submit the question without displaying it.

Go to MarkBind's User Guide -> Using Components -> Others -> Quizzes. Start the quiz and answer the first question. Press next multiple times and it will skip some questions, in my case until the end of the quiz.

ezgif com-video-to-gif

### Expected behavior

The quiz goes to the next question without skipping any question regardless of type.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lesterong**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**

Only allow the click event on the Next button in Quiz to be triggered once. Resolves #2188. 

**Anything you'd like to highlight/discuss:**

NIL

**Testing instructions:**

NIL

**Proposed commit message: (wrap lines at 72 characters)**

Fix Quiz next button skipping questions 

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Comment by yucheng11122017** [comment]
Hi @lesterong thanks very much for the work on this PR! 
Gentle reminder not to delete the PR template when creating a PR :) You can just fill in nil for things if there's nothing to add and so on. 
Also, could you try to add unit tests for this PR? Thanks!

**Comment by lesterong** [comment]
> Hi @lesterong thanks very much for the work on this PR! Gentle reminder not to delete the PR template when creating a PR :) You can just fill in nil for things if there's nothing to add and so on. Also, could you try to add unit tests for this PR? Thanks!

@yucheng11122017, noted on that! I have edited my comment with the full template. Also, may I clarify what unit tests to add? It seems like the tests for the `Quiz` component were skipped in an earlier pull request #2244.

**Comment by itsyme** [comment]
> > Hi @lesterong thanks very much for the work on this PR! Gentle reminder not to delete the PR template when creating a PR :) You can just fill in nil for things if there's nothing to add and so on. Also, could you try to add unit tests for this PR? Thanks!
> 
> @yucheng11122017, noted on that! I have edited my comment with the full template. Also, may I clarify what unit tests to add? It seems like the tests for the `Quiz` component were skipped in an earlier pull request #2244.

hi @lesterong! the tests were disabled due to some unexpected behaviour with setTimeout being used in the tests causing CI to fail sometimes. perhaps you could test the fix locally but skip it when you commit

**Comment by tlylt** [comment]
Checked on https://deploy-preview-2312--markbind-master.netlify.app/userguide/components/others#quizzes and the behavior seems to be corrected 👍

**Review by yucheng11122017 — APPROVED** [review]
LGTM! Thanks @lesterong

**Comment by itsyme** [comment]
LGTM! I've checked out the tests as well and it seems to work as intended. Thanks @lesterong!

**Review by itsyme — APPROVED** [review]

**Comment by itsyme** [comment]
@all-contributors please add lesterong for code

**Pull request merged**
