### PR TITLE
Add DG to markbind.org

### LINKED ISSUE #1161: Link to DevGuide in markbind.org
**Is your request related to a problem?**

Currently we have no easy access to the developer's guide from markbind.org. It would be better if developer's guide along with contribution guide can be easily accessible from the official website.

### PR DESCRIPTION
**Pull request by Tejas2805**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Documentation update
• [x] Bug fix

Fixes #1161 

**What is the rationale for this request?**
The site markbind.org doens't have a developer guide.

**What changes did you make? (Give an overview)**
Added developer guide to the site.

**Provide some example code that this change will affect:**

N.A.

**Is there anything you'd like reviewers to focus on?**
N.A.

**Testing instructions:**
Not sure. 

**Proposed commit message: (wrap lines at 72 characters)**
```
The site markbind.org doesn't provide access to
developer guide.

Let's add the developer guide to the site, so that the
developer guide along with the contribution guide is
accessible from official website.
```

### CODE REVIEW

**Comment by damithc** [comment]
Is [this requirement](https://github.com/MarkBind/markbind/issues/1161#issuecomment-614434564) satisfied?

**Comment by Tejas2805** [comment]
> Is [this requirement](https://github.com/MarkBind/markbind/issues/1161#issuecomment-614434564) satisfied?

I think so. Just waiting for one reviewer to review and confirm the same.

**Comment by Tejas2805** [comment]
Based on what I tried locally, this works!

**Comment by nbriannl** [comment]
> Keep in mind the UG should follow the latest released version while DG should follow the master branch.

Is this satisfied? It seems the current implementation is building the DG pages as part of ug-site generation. This would mean that the DG would only follow the latest released version.

I might be wrong however.

**Comment by le0tan** [comment]
From what I’ve seen in [markbind.org repo](https://github.com/MarkBind/markbind.github.io), the site generation only happens at every release. So basically DG is not updated more frequently than UG unless we change the trigger for Travis.

**Comment by Tejas2805** [comment]
> From what I’ve seen in [markbind.org repo](https://github.com/MarkBind/markbind.github.io), the site generation only happens at every release. So basically DG is not updated more frequently than UG unless we change the trigger for Travis.

But won't this affect UG too then?

**Comment by nbriannl** [comment]
For this PR, you could update the Navbar and SiteNav to contain links to the DG hosted at https://markbind.org/devdocs/

**Comment by damithc** [comment]
The current solution: we only generate DG in netlify version because netlify version is always up to date with master branch. DG is omitted in the version deployed to markbind.org because that version can be behind the master branch. Hence, developers looking to read the DG should be directed to the netlify version even if the link to the DG is given in the markbind.org.

Anyway, that's the current solution. Not wedded to it if there is a better alternative.

**Comment by damithc** [comment]
> The current solution: we only generate DG in netlify version because netlify version is always up to date with master branch. DG is omitted in the version deployed to markbind.org because that version can be behind the master branch. Hence, developers looking to read the DG should be directed to the netlify version even if the link to the DG is given in the markbind.org.
> 
> Anyway, that's the current solution. Not wedded to it if there is a better alternative.

Not sure if things changed recently though. The above was the situation sometime back. @yamgent might remember better.

**Comment by Tejas2805** [comment]
@nbriannl Do you mean something along these lines?

**Comment by nbriannl** [comment]
> @nbriannl Do you mean something along these lines?

Yeah. This isn't complete though, because I believe you need to do `userGuide/header.md`

**Comment by Tejas2805** [comment]
> Yeah, along this line! This isn't complete though, because I believe you need to do `userGuide/header.md`

I was just confirming if you had something like this in your mind. Have implemented the rest.

**Comment by marvinchin** [comment]
Thanks for trying to address this! Sorry I haven't been able to respond sooner.

After looking at the concerns raised above, I think fiddling with the links might not be worth the effort, and it might make the site harder to maintain. Perhaps we can just add a page that directs potential contributors to our GitHub page (this can be a hard link), and update the README to point them to the netlify version with the DG. This would help direct potential contributors to the necessary resources without much added complexity.

**Comment by damithc** [comment]
Agree with @marvinchin 
Given DG updates are rare, it may be OK for the links to be broken in netlify preview, if the alternative solutions are costly.  Netlify previews are used by the reviewers only.

**Pull request closed without merging**
