### PR TITLE
Update UG and DG site json file to include new plugins

### PR DESCRIPTION
**Pull request by EltonGohJH**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Fixes https://github.com/MarkBind/markbind/issues/2451
Update UG and DG site json file to include new plugins

**Anything you'd like to highlight/discuss:**
I realised that these plugins are not enabled after looking at issue #2529 which is kinda ironic.

**Testing instructions:**
Merge to master to test. Quite confident this will solve it 😆 

**Proposed commit message: (wrap lines at 72 characters)**
Update UG and DG site json file to include new plugins

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [x] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Review by kaixin-hc — APPROVED** [review]
lgtm lmao I wish we merged this earlier

**Comment by damithc** [comment]
> I realised that these plugins are not enabled after looking at issue #2529 which is kinda ironic.

Good catch, @EltonGohJH 

>lgtm lmao I wish we merged this earlier 

I guess we need to do another release? :-p

**Comment by damithc** [comment]
> @kaixin-hc is thinking of doing a release after that if there are any changes.

It's best to fix the UG though, if not through a release, then by doing a manual update.

**Comment by tlylt** [comment]
@EltonGohJH does our DG use any of the added plugins? Especially the ones like web3Form? I believe that's the reason why some of these are not added to our DG.

In addition, I think it's fine that we don't include the newly included `datatable` or `mermaid` plugins if we don't use them. It should be a valid use case where users can opt to remove the plugins in the site.json file and MarkBind will still work? If so our docs will successfully illustrate that.

**Comment by EltonGohJH** [comment]
@tlylt 
I added because I thought it should be consistent but on hindsight maybe I should have only enabled what is used. I agree that our DG can serve as use case for the behaviour for site.json.

**Pull request merged**
