### PR TITLE
Fix reload inconsistency when updating frontmatter

### LINKED ISSUE #1001: Inconsistent reloading of site on updating frontmatter
* **MarkBind Version:**
MarkBind 2.9.1

**What did you do? Please include the actual source code causing the issue.**
* Created a MarkBind site using the default template: `markbind init --template default`
* Edited `index.md` to use the default layout on that page by replacing `header: header.md` with `layout: default`. 
* Executed `markbind serve`
* `index.html` w/o header live-reloads correctly.
* Replaced default layout(`layout: default`) with header in frontmatter (`header: header.md`) 
* `index.html` live-reloads with the header, as expected
* Retried using the default layout on that page by replacing `header: header.md` with `layout: default`

(same results with `footer: footer.md`)

```html
<frontmatter>
  layout: default
  pageNav: 2
  pageNavTitle: "Chapters of This Page"
  siteNav: site-nav.md
</frontmatter>
```

**What did you expect to happen?**
The default layout to take over and the original header/footer in `header.md`/`footer.md` to not take effect.

**What actually happened? Please include the actual, raw output.**
The header/footer doesn't get removed.
However, if I disconnect the sever and re-run `markbind build` / `markbind serve`, the change is reflected i.e. the `default` layout is rendered instead of the header in `header.md`.

If this behaviour is intentional, perhaps we can document it under `Frontmatter` or `Page Layouts`?

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**
• [X] Bug fix

**What is the rationale for this request?**
See proposed commit message below. This fixes #1001.

**What changes did you make? (Give an overview)**
The frontmatter files for the site templates are populated.

**Is there anything you'd like reviewers to focus on?**
This is just #1035 reopened, with proper branch management on my part, following advice from @ang-zeyu.

**Testing instructions:**
See topic opener for #1001.

**Proposed commit message: (wrap lines at 72 characters)**
Fix reload inconsistency when updating frontmatter

The header, footer and navigation frontmatter for the minimal and
default site templates are empty. This causes inconsistent reloading
when the frontmatter is changed (#1001). Here we populate said
frontmatter.

### CODE REVIEW

**Comment by crphang** [comment]
@Parcly-Taxel could we also add this to the `collectAllPageSections`? 

```diff
Page.prototype.collectAllPageSections = function () {
+ this.pageSectionsHtml = {}; // This resets the pageSectionsHTML whenever we collect.
  this.collectPageSection('header');
  this.collectPageSection(`#${SITE_NAV_ID}`);
  this.collectPageSection('footer');
};
```

This ensures that each reload always reset the pageSections and reduce the dependency on how templates are created which could potentially be crowd-sourced. While you're at it, could you also add `<header>` and `<footer`> to minimal template? 

Thanks for your contribution!

**Comment by Parcly-Taxel** [comment]
> could we also add this to the `collectAllPageSections`?
>
> ```diff
> Page.prototype.collectAllPageSections = function () {
> + this.pageSectionsHtml = {}; // This resets the pageSectionsHTML whenever we collect.
>   this.collectPageSection('header');
>   this.collectPageSection(`#${SITE_NAV_ID}`);
>   this.collectPageSection('footer');
> };
> ```

@crphang done, but @ang-zeyu said in #1035 to "go the other way", i.e. "add `<header>` and `<footer>` to minimal template", which I had already done before closing the original PR.

**Comment by ang-zeyu** [comment]
> @crphang done, but @ang-zeyu said in #1035 to "go the other way", i.e. "add `<header>` and `<footer>` to minimal template", which I had already done before closing the original PR.

You could do both https://github.com/MarkBind/markbind/issues/1001#issuecomment-582775751 :)

The fix I suggested was merely to remove `{{ timestamp }}` from the footer(s), which would cause your tests to fail irregardless
And also to add the changes to the minimal template for consistency since the default template is also getting "the other fix". ( markbind has 2 templates )

**Comment by Parcly-Taxel** [comment]
> You could do both [#1001 (comment)](https://github.com/MarkBind/markbind/issues/1001#issuecomment-582775751) :)
> 
> The fix I suggested was merely to remove `{{ timestamp }}` from the footer(s), which would cause your tests to fail irregardless
> And also to add the changes to the minimal template for consistency since the default template is also getting "the other fix". ( markbind has 2 templates )

@ang-zeyu yes, can we merge this now?

**Comment by ang-zeyu** [comment]
> yes, can we merge this now, since I have done both?

Looks good to me 👍

I don't have merging powers here though, you'd have to wait for a maintainer to merge this in!

**Comment by Parcly-Taxel** [comment]
> > yes, can we merge this now, since I have done both?
> 
> Looks good to me +1
> 
> I don't have merging powers here though, you'd have to wait for a maintainer to merge this in!

Can't you approve it first?

**Pull request merged**
