### PR TITLE
Fix anchor navigation in panel headers

### LINKED ISSUE #1071: Anchor navigation in panel not working properly with fixed header
**Tell us about your environment**

* **MarkBind Version:**2.11.0

**What did you do? Please include the actual source code causing the issue.**
1. Fix the header with `<header class="header-fixed">` in `header.md`
2. Include the following content
```html
<panel header="## Hello">
</panel>
```

**What did you expect to happen?**

Anchor navigation on "Hello" should work properly.

**What actually happened? Please include the actual, raw output.**

Clicking the anchor would place the title under the top navbar.

### LINKED ISSUE #1104: Heading hidden when clicking pageNav
Happens when the heading is in a panel header and the topNav is in fixed mode.
pageNav-glitch

### PR DESCRIPTION
**Pull request by le0tan**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Documentation update
• [X] Bug fix

Fixes #1104 Fixes #1071 

**What is the rationale for this request?**

Re-implement the anchor navigation fix for fixed headers using pseudo selectors, so that no runtime generation of dummy spans is no longer needed.

**What changes did you make? (Give an overview)**

Instead of adding a invisible dummy span, we introduce the empty space using `::before` css selector. For the special case of panel headers, we add `::before` to the container so that when the `scrollToUrlAnchorHeading` function locates the target as the container, the offset is correctly applied.

**Is there anything you'd like reviewers to focus on?**

This change should only affect the behavior when `class="header-fixed"` is set in `header.md`'s `<header>`. Test if there are unexpected issues of anchor navigation.

**Important**: I applied the css to `.card-container`, not sure if there are any other vue-strap components that uses this class name and is affected unexpectedly.

**Testing instructions:**

Replace the vue-strap file from https://github.com/MarkBind/vue-strap/pull/141

**Proposed commit message: (wrap lines at 72 characters)**

To avoid generating lots of dummy spans at runtime when fixed header is
enabled, and to fix the bug where anchor navigation doesn't work when
the panel is minimized, we re-implement the anchor nav fix using
::before selector.

Let's introduce the invisible empty space by applying styles to
::before of h tags and card-containers.

Let's disable the pointer-events of the card-container to prevent users
from clicking on the invisible empty space; and force the
pointer-events to all on the button space of the panel. (See the
companion vue-strap commit)

### CODE REVIEW

**Comment by ang-zeyu** [comment]
Have you tried the solution adopted here? ( notice the `::before` )
https://getbootstrap.com/docs/4.1/getting-started/introduction/

I tried it briefly on the inspector, it seems to work well as a css-only solution for both minimized and expanded panel forms:
panel-id

Could this be used instead of creating spans at runtime?

**Comment by le0tan** [comment]
@ang-zeyu you were adding `::before` to the card container instead of the `h` tag - but that's indeed a good idea. I'm trying to work out an impl using it.

**Comment by ang-zeyu** [comment]
> @ang-zeyu you were adding `::before` to the card container instead of the `h` tag

This is due to how we assign the id of the header to the root of the panel ( `card-container` ) as well, which is necessary as a panel's `alt` may not necessarily be the `header` as well. 

You can refer to #967 for a more in depth disccussion.

> Edit: I added `::before` to both `<h>` tags and `span` tags. Can you kindly review before I resolve conflicts in the test sites?

👍 will take a look in a while

**Comment by ang-zeyu** [comment]
Seems good, for headings inside panels, you would also need to add `pointer-events: none` css ( in vue-strap ) or something of the sort though, to prevent the user from being able to click the `::before` element and expand the panel.

**Comment by le0tan** [comment]
> Seems good, for headings inside panels, you would also need to add `pointer-events: none` css ( in vue-strap ) or something of the sort though, to prevent the user from being able to click the `::before` element and expand the panel.

Good catch! Will rectify this shortly. Thanks!

**Pull request closed without merging**
