### PR TITLE
Add appId to Algolia plugin

### PR DESCRIPTION
**Pull request by jonahtanjz**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

Addresses #1729 
**Overview of changes:**
Algolia now requires `appId` to be provided in order to use its APIs. Add `appId` to Algolia plugin's options.

**Anything you'd like to highlight / discuss:**
`NIL`

**Testing instructions:**
Add the following to `site.json`, add `algolia` attribute to searchbar and serve the site.
```json
"plugins": [
    "algolia"
  ],
  "pluginsContext": {
    "algolia": {
      "apiKey": "599cec31baffa4868cae4e79f180729b",
      "appId": "R2IYF7ETH7",
      "indexName": "docsearch"
    }
  }
```

**Proposed commit message: (wrap lines at 72 characters)**
Add appId to Algolia plugin's options

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Review by ang-zeyu — APPROVED** [review]
LGTM 👍

**Comment by damithc** [comment]
@jonahtanjz thanks for tackling this. But it looks like adding `appId` is not enough to get the module website working for this semester; I should be able to pass in  the `facetFilters` parameter as well. If not, search results will contain results from all of my module websites, not just the target module. This is because Algolia has unified all my search indexes to one (we were given separate indexes for each website before).
image

**Comment by jonahtanjz** [comment]
Prof @damithc, try putting the `facetFilters` in `algoliaOptions` instead of `searchParameters`.
```json
"pluginsContext": {
    "algolia": {
      "apiKey": "a3fef7e2d9dea07c0fa2d8ed521057aa",
      "appId": "3DU4XTBX4T",
      "indexName": "nus-tic-cs",
      "algoliaOptions": {
        "facetFilters": ["site:nus-tic2002-2022.github.io"]
      }
    }
  }
```

**Comment by damithc** [comment]
> Prof @damithc, try putting the `facetFilters` in `algoliaOptions` instead of `searchParameters`.

Ah, that seems to work. Thanks @jonahtanjz

**Pull request merged**
