### PR TITLE
Update placement of Onboarding in dev docs

### PR DESCRIPTION
**Pull request by charandeepsinghb**
**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Fixes: #2071

**Anything you'd like to highlight/discuss:**
The onboarding doc is placed at the bottom of the site-nav.
To be more prominent and visible for potentially new contributors.
Moved the 'Onboarding Bootcamp' section below 'Contributing' section.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Update placement of Onboarding in dev docs

---

**Checklist:** :ballot_box_with_check:

- [x] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

**Comment by raysonkoh** [comment]
Great first PR @charandeepsinghb! Just need to make one small change (details in the original issue) and you are good to go! 🚀

**Review by tlylt — CHANGES_REQUESTED** [review]
The navigation buttons at the bottom of the pages will need to be updated since they are manually determined and now that the page order has changed, they are not reflecting the correct sequence anymore. This impacts other pages before/after the onboarding part (before and after this change as well)

image

**Comment by charandeepsinghb** [comment]
Updated the next and previous buttons on pages.

**Review by raysonkoh — APPROVED** [review]
LGTM! Thank you for contributing, @charandeepsinghb!

**Review by tlylt — APPROVED** [review]

**Comment by raysonkoh** [comment]
@all-contributors please add charandeepsinghb for code

**Comment by raysonkoh** [comment]
@all-contributors please add charandeepsinghb for doc

**Pull request merged**
