### PR TITLE
Migrate core/src/lib/markdown-it to TypeScript

### PR DESCRIPTION
**Pull request by yucheng11122017**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [X] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Part of https://github.com/MarkBind/markbind/issues/1913

**Overview of changes:**
Migrates core/src/lib/markdown-it to TypeScript

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Rebase commit

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes

### CODE REVIEW

**Comment by raysonkoh** [comment]
Thanks @yucheng11122017 for the help with the TS migration! There seems to be quite a lot of JS files to be migrated in `lib/markdown-it/`. Are you planning to do this migration over a series of PRs?

**Comment by yucheng11122017** [comment]
Hi @raysonkoh I think per #1913, the other files aren't stated to be migrated to TS because they are mostly from other source codes. Is this ok or should I do the rest as well?

**Review by EltonGohJH — APPROVED** [review]
LGTM

**Comment by raysonkoh** [comment]
Right, should be fine to migrate these files over first then.

**Review by raysonkoh — COMMENTED** [review]
Seems like there is too much code diff in your `index.ts`. Under "files changed", it is now showing `index.js` as deleted instead of renamed. Can you check if you have formatted the code in `index.ts`?

Edit: ignore this, see comment below

**Comment by jovyntls** [comment]
@yucheng11122017 There's a merge commit in between your "Adapt" and "Rename" commits. Can you rebase your branch on master to remove this merge commit? Since we're using the rebase commit strategy to merge PRs, we only want to clean commits (Rename+Adapt) here :)

**Comment by yucheng11122017** [comment]
Sorry I'm having some problems with squashing the merge conflict properly. When it is squashed, some of the latest changes that were merged into master are included in the PR. Is any way to fix this issue? Thank you!

**Pull request closed without merging**
