### PR TITLE
Fix backslash bugs in convert feature

### LINKED ISSUE #1736: While using markbind convert, some `/` end up as `\`
**Tell us about your environment**
Windows 10

* **MarkBind Version:**
v3.1.0

**What did you do? Please include the actual source code causing the issue.**
I noticed that some of the href links in the markbind/layouts/default.md file are wrongly assigned as `%5C` which is `\`. 

image

**What did you expect to happen?**

The intended is clearly `/` but due to the way windows shows it directories, there is some issues 
when looking at the addressable page path. 

**What actually happened? Please include the actual, raw output.**

`<a href="/contents%5Ctopic1.html">Topic 1</a></div>` example of wrong output.

I will be working on the fix to this as well.

### PR DESCRIPTION
**Pull request by ong6**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] Others, please explain:

Fixes #1736 

**Overview of changes:**

Updated the relativePagePath to ensure that no unnecessary `\` were being made. Done by updating a function from fsUtil

**Anything you'd like to highlight / discuss:**

**Testing instructions:**

Run `markbind init -convert` on a test repo and make sure there are no instances of `\` or `%5C` in the `layouts/default.md` file.
Build and see that there also should not have any instance of `\` or `%5C`

**Proposed commit message: (wrap lines at 72 characters)**

Resolved bug regarding backslashes in convert feature

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features (will be done in another PR)
- [x] Linked all related issues
- [x] No unrelated changes

### CODE REVIEW

**Review by jonahtanjz — APPROVED** [review]
Saw that in one of the commits you updated the package-lock.json. Is there a reason for that?

Otherwise, LGTM 👍

**Comment by ong6** [comment]
> Saw that in one of the commits you updated the package-lock.json. Is there a reason for that?
> 
> Otherwise, LGTM 👍

I thought my package-lock.json was failing the Appveyor build. But then realized it was another issue altogether. Also, I think zeyu asked me to remove some lines from the PR #1727.

**Comment by jonahtanjz** [comment]
Thanks for clarifying @ong6 :)

**Comment by ang-zeyu** [comment]
> I thought my package-lock.json was failing the Appveyor build. But then realized it was another issue altogether. Also, I think zeyu asked me to remove some lines from the PR #1727.

https://github.com/MarkBind/markbind/pull/1727#discussion_r795207110 Sorry for the ambiguous wording.

To clarify, I meant removing the diffs. (same rationale as https://github.com/MarkBind/markbind/pull/1679#discussion_r725468509)

fyi, the issue with appveyor: `https://github.com/actions/setup-node/issues/411`
I think we can make a mental note of testing the windows build locally for now and ignore the failing builds @jonahtanjz @ryoarmanda

**Comment by ang-zeyu** [comment]
I've reverted the package-lock changes from #1728, which seems to be causing the changes here.
You can remove the diffs by merging in the latest changes too :)

**Pull request merged**
