### PR TITLE
Fix stray space before popover and tooltip

### LINKED ISSUE #2419: Tooltips seem to add an extra space in front
code: `(<tooltip content="abc">why?</tooltip>)`
output:
image

problem: there is an extra space between `(` and `w`?

PS: noticed the same issue with popevers

image

### PR DESCRIPTION
**Pull request by yiwen101**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Resolve #2419, modified vue(modification made at minimal scope via trial and error) and add test; 
Credit to @kaixin-hc for investigating the cause of the bug.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**
Test with `markbind serve -d`

**Proposed commit message: (wrap lines at 72 characters)**
Fix stray space before popover and tooltip

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Review by EltonGohJH — APPROVED** [review]
LGTM!

Good job in finding a solution to this bug. 
I am just thinking whether we can do better as I think that future devs may be confuse why there is a comment there. Maybe gitblame will be enough but I am thinking whether we can do more.

**Comment by tlylt** [comment]
> as I think that future devs may be confuse why there is a comment there

I agree, not obvious and could be accidentally deleted in the future. @yiwen101 could you note the reason inside the comment pls?

**Comment by yiwen101** [comment]
@tlylt @EltonGohJH 
Thank you for the valuable suggestions. I have improve the comment.

**Review by tlylt — APPROVED** [review]

**Review by kaixin-hc — APPROVED** [review]
Great - merging!

**Pull request merged**
